In [1]:
#Import dependencies

#Import basic modules
import numpy as np
import pandas as pd
from datetime import datetime

#Import graphing modules
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline


#Sci-Kit-Learn dependencies
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit

#Machine Learning/Data Mining Models
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

#Evaluation and validation
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
#Word Development Indicators dataframe

WDI_df = pd.read_csv('WDIData.csv')
WDI_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 63
0,Arab World,ARB,"2005 PPP conversion factor, GDP (LCU per inter...",PA.NUS.PPP.05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"2005 PPP conversion factor, private consumptio...",PA.NUS.PRVT.PP.05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,82.407647,82.827636,83.169227,83.587141,83.954293,84.230630,84.570425,NaN,NaN,NaN
3,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,86.136134,86.782683,87.288244,88.389705,88.076774,88.517967,88.768654,NaN,NaN,NaN
4,Arab World,ARB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,74.543489,75.770972,76.772916,78.839139,77.487377,78.564439,78.958780,NaN,NaN,NaN

In [3]:
#DataFrame exploration

print(WDI_df.info())
WDI_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 422136 entries, 0 to 422135
Data columns (total 64 columns):
Country Name      422136 non-null object
Country Code      422136 non-null object
Indicator Name    422136 non-null object
Indicator Code    422136 non-null object
1960              38296 non-null float64
1961              42017 non-null float64
1962              44198 non-null float64
1963              44084 non-null float64
1964              44611 non-null float64
1965              47305 non-null float64
1966              46902 non-null float64
1967              48633 non-null float64
1968              48209 non-null float64
1969              50011 non-null float64
1970              92892 non-null float64
1971              99126 non-null float64
1972              101898 non-null float64
1973              101523 non-null float64
1974              102838 non-null float64
1975              106739 non-null float64
1976              108656 non-null float64
1977              111988 non-null float64
1978              111568 non-null float64
1979              112371 non-null float64
1980              117218 non-null float64
1981              119130 non-null float64
1982              120334 non-null float64
1983              120112 non-null float64
1984              120914 non-null float64
1985              122087 non-null float64
1986              122924 non-null float64
1987              124326 non-null float64
1988              124043 non-null float64
1989              125804 non-null float64
1990              150283 non-null float64
1991              155342 non-null float64
1992              159292 non-null float64
1993              160651 non-null float64
1994              162800 non-null float64
1995              170546 non-null float64
1996              170804 non-null float64
1997              171881 non-null float64
1998              173814 non-null float64
1999              179128 non-null float64
2000              203655 non-null float64
2001              193654 non-null float64
2002              198571 non-null float64
2003              199394 non-null float64
2004              204796 non-null float64
2005              218727 non-null float64
2006              216489 non-null float64
2007              220471 non-null float64
2008              219495 non-null float64
2009              220308 non-null float64
2010              235880 non-null float64
2011              226320 non-null float64
2012              227731 non-null float64
2013              222939 non-null float64
2014              227702 non-null float64
2015              221790 non-null float64
2016              212990 non-null float64
2017              186601 non-null float64
2018              30247 non-null float64
Unnamed: 63       0 non-null float64
dtypes: float64(60), object(4)
memory usage: 206.1+ MB
None

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 63
count,3.829600e+04,4.201700e+04,4.419800e+04,4.408400e+04,4.461100e+04,4.730500e+04,4.690200e+04,4.863300e+04,4.820900e+04,5.001100e+04,...,2.358800e+05,2.263200e+05,2.277310e+05,2.229390e+05,2.277020e+05,2.217900e+05,2.129900e+05,1.866010e+05,3.024700e+04,0.0
mean,2.452211e+11,2.425950e+11,2.449366e+11,2.529916e+11,2.709654e+11,2.865474e+11,3.106604e+11,3.252888e+11,3.777535e+11,4.088952e+11,...,1.657079e+12,1.932391e+12,2.069415e+12,2.351690e+12,2.499325e+12,2.668441e+12,3.025145e+12,3.572197e+12,3.223694e+10,NaN
std,1.001513e+13,1.049264e+13,1.094735e+13,1.150925e+13,1.238989e+13,1.368799e+13,1.513324e+13,1.651773e+13,1.902679e+13,2.151339e+13,...,7.063430e+13,8.063045e+13,8.695864e+13,9.978061e+13,1.096046e+14,1.163139e+14,1.314594e+14,1.498426e+14,1.039081e+12,NaN
min,-3.344191e+14,-3.823000e+14,-4.327955e+14,-4.769875e+14,-5.339358e+14,-6.264716e+14,-7.120024e+14,-8.245134e+14,-9.379467e+14,-1.122499e+15,...,-1.827709e+14,-2.168927e+14,-3.013845e+14,-3.495617e+14,-5.189385e+14,-8.530882e+14,-1.374105e+15,-1.345846e+15,-4.386237e+01,NaN
25%,4.280341e+00,4.607864e+00,4.542384e+00,4.761900e+00,4.842686e+00,4.651163e+00,4.875091e+00,4.761900e+00,5.044458e+00,4.535321e+00,...,4.900000e+00,5.368712e+00,5.000000e+00,5.107259e+00,5.078215e+00,5.223753e+00,4.932370e+00,4.900000e+00,7.000000e+00,NaN
50%,3.556376e+01,3.697289e+01,3.598862e+01,3.553986e+01,3.660237e+01,3.863287e+01,3.981183e+01,4.136048e+01,4.220797e+01,3.932502e+01,...,4.245403e+01,4.711836e+01,4.629863e+01,4.664437e+01,4.725001e+01,4.688376e+01,4.665330e+01,4.856844e+01,3.297873e+01,NaN
75%,2.479780e+05,2.248010e+05,1.441955e+05,1.967100e+05,2.400000e+05,3.778000e+05,4.739790e+05,4.560170e+05,6.795970e+05,5.876463e+05,...,2.500000e+05,5.396312e+05,4.566098e+05,6.809700e+05,3.751433e+05,5.440110e+05,1.044740e+06,6.284045e+06,8.131200e+01,NaN
max,8.353728e+14,9.312536e+14,1.011252e+15,1.084815e+15,1.184553e+15,1.388505e+15,1.544572e+15,1.724250e+15,1.979579e+15,2.302920e+15,...,6.864133e+15,7.831726e+15,8.676844e+15,1.000180e+16,1.155185e+16,1.167182e+16,1.319219e+16,1.534503e+16,6.817944e+13,NaN

Given the structure of the data, .describe() doesn't really give relevant information

Performing a groupping  by 'Country Code' will allow to check whether there are equal amount of rows per country, in which case it is safer to assume that there are as many indicators for each of the countries.

In [4]:
WDI_df.groupby('Country Code').count()

,Country Name,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 63
Country Code,,,,,,,,,,,,,,,,,,,,,
ABW,1599,1599,1599,87,88,90,88,88,91,88,...,483,440,432,423,408,375,366,257,13,0
AFG,1599,1599,1599,171,185,198,200,204,217,207,...,986,1008,994,954,994,999,935,933,130,0
AGO,1599,1599,1599,135,142,148,140,131,146,141,...,1146,1115,1010,1004,1051,1004,1003,866,134,0
ALB,1599,1599,1599,105,111,116,111,111,115,109,...,1158,1168,1225,1170,1144,1134,1064,1000,144,0
AND,1599,1599,1599,11,16,18,16,16,21,16,...,235,210,210,213,245,220,207,131,13,0
ARB,1599,1599,1599,138,153,159,160,159,165,161,...,728,686,701,680,733,680,667,597,105,0
ARE,1599,1599,1599,106,120,125,120,121,121,123,...,641,673,719,705,722,683,703,574,109,0
ARG,1599,1599,1599,215,228,268,265,269,301,299,...,1190,1143,1164,1117,1139,1052,1035,811,141,0
ARM,1599,1599,1599,84,85,87,85,85,87,85,...,1259,1222,1202,1209,1178,1152,1131,1010,134,0
ASM,1599,1599,1599,23,27,27,27,27,30,27,...,165,148,147,139,141,139,135,123,13,0
ATG,1599,1599,1599,101,105,110,105,105,108,108,...,674,613,622,531,616,589,508,511,56,0
AUS,1599,1599,1599,251,289,288,297,297,304,307,...,926,861,870,856,880,876,827,708,115,0
AUT,1599,1599,1599,204,228,230,240,241,254,249,...,912,889,890,877,914,899,829,714,114,0
AZE,1599,1599,1599,84,85,87,85,85,87,85,...,1154,1133,1138,1113,1095,1059,1014,920,129,0
BDI,1599,1599,1599,160,174,195,191,202,228,217,...,1149,1063,1080,1056,1139,1019,1010,845,123,0
BEL,1599,1599,1599,181,189,199,199,199,210,208,...,929,876,881,892,913,895,828,657,109,0
BEN,1599,1599,1599,208,250,261,268,274,277,274,...,1135,1145,1129,1076,1085,1051,1017,871,137,0
BFA,1599,1599,1599,184,206,238,240,229,264,277,...,1175,1087,1093,1077,1206,1102,1070,980,123,0
BGD,1599,1599,1599,175,209,207,202,202,205,202,...,1247,1171,1108,1239,1106,1095,1148,1014,138,0
BGR,1599,1599,1599,102,114,119,116,118,130,119,...,1191,1148,1142,1142,1132,1084,1062,886,132,0
BHR,1599,1599,1599,109,117,122,117,117,135,131,...,821,823,788,796,789,778,756,647,113,0
BHS,1599,1599,1599,124,129,145,155,152,149,153,...,796,672,672,664,682,684,742,578,108,0
BIH,1599,1599,1599,82,83,85,83,83,85,83,...,1146,1145,1133,1079,1113,1079,1060,941,133,0
BLR,1599,1599,1599,86,85,87,85,85,89,85,...,1179,1131,1199,1173,1149,1128,1112,1028,134,0
BLZ,1599,1599,1599,133,139,147,153,152,166,163,...,1105,1057,1078,1078,1081,1092,1082,973,125,0
BMU,1599,1599,1599,41,65,68,66,76,83,79,...,447,411,421,352,269,238,221,162,17,0
BOL,1599,1599,1599,205,237,258,255,250,256,254,...,1110,1183,1208,1157,1162,1181,1087,1017,139,0
BRA,1599,1599,1599,242,257,274,270,271,283,285,...,1118,1239,1201,1222,1246,1250,1134,992,199,0
BRB,1599,1599,1599,107,125,132,125,124,129,144,...,789,708,679,649,636,634,583,473,105,0
BRN,1599,1599,1599,120,122,141,136,135,146,138,...,742,723,707,686,792,704,728,693,108,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TLA,1599,1599,1599,182,196,212,209,211,226,226,...,800,787,797,785,809,783,760,697,151,0
TLS,1599,1599,1599,80,104,101,96,96,97,96,...,1085,1008,988,1051,1014,1012,1013,822,112,0
TMN,1599,1599,1599,153,173,180,186,180,193,204,...,780,698,696,690,726,698,702,611,109,0
TON,1599,1599,1599,106,113,115,115,116,124,127,...,898,873,900,850,817,863,779,688,120,0
TSA,1599,1599,1599,195,229,239,237,239,246,240,...,831,740,791,746,767,746,724,650,110,0
TSS,1599,1599,1599,152,169,176,174,175,186,182,...,784,724,740,718,728,686,669,602,109,0
TTO,1599,1599,1599,150,174,183,179,180,188,202,...,793,680,680,669,658,650,581,490,113,0
TUN,1599,1599,1599,145,158,176,178,182,304,316,...,1221,1128,1196,1088,992,1005,958,827,140,0
TUR,1599,1599,1599,249,259,275,277,280,293,281,...,1258,1231,1220,1259,1228,1202,1143,967,142,0
TUV,1599,1599,1599,13,19,19,19,19,22,19,...,327,276,290,284,280,282,304,171,19,0
TZA,1599,1599,1599,136,148,157,155,157,173,171,...,1187,1091,1126,1113,1198,1011,1031,927,125,0
UGA,1599,1599,1599,195,204,215,221,226,236,240,...,1093,1096,1168,1078,1030,1062,1089,1004,131,0
UKR,1599,1599,1599,86,85,87,85,85,93,89,...,1182,1192,1244,1193,1182,1101,1103,998,135,0
UMC,1599,1599,1599,184,199,203,199,199,205,207,...,1012,947,955,942,969,942,908,852,134,0
URY,1599,1599,1599,222,244,252,253,250,270,264,...,1029,946,928,953,976,946,904,796,114,0
USA,1599,1599,1599,253,271,288,288,288,297,288,...,931,879,896,923,919,895,851,642,159,0
UZB,1599,1599,1599,86,87,89,87,87,89,87,...,939,945,967,977,991,974,946,867,129,0
VCT,1599,1599,1599,117,128,135,130,130,133,130,...,979,878,886,961,946,983,969,908,122,0
VEN,1599,1599,1599,224,264,279,281,277,286,279,...,1113,1078,1067,1037,993,816,777,617,136,0
VGB,1599,1599,1599,24,31,39,39,38,34,39,...,122,109,97,93,105,111,91,75,13,0
VIR,1599,1599,1599,98,104,106,104,104,107,104,...,249,233,234,226,226,228,205,155,61,0
VNM,1599,1599,1599,135,145,153,142,138,143,140,...,1197,1109,1195,1111,1157,1082,1031,916,139,0
VUT,1599,1599,1599,102,114,126,122,137,139,137,...,982,892,914,928,901,893,735,668,117,0
WLD,1599,1599,1599,179,197,213,209,209,215,212,...,819,764,769,756,774,744,708,651,101,0
WSM,1599,1599,1599,97,124,131,130,142,148,155,...,912,911,934,841,958,925,925,857,117,0
XKX,1599,1599,1599,2,5,5,5,5,5,5,...,647,671,696,692,699,678,668,620,60,0
YEM,1599,1599,1599,112,123,129,124,128,135,129,...,1063,932,943,999,897,832,831,656,111,0
ZAF,1599,1599,1599,283,305,313,313,313,328,325,...,1220,1145,1134,1107,1186,1174,1116,990,186,0
ZMB,1599,1599,1599,137,152,159,160,192,227,244,...,1150,1046,1057,1056,1020,1018,959,915,138,0
ZWE,1599,1599,1599,142,164,162,169,196,228,218,...,1035,1138,1130,1017,1030,1042,999,893,126,0

To verify this .unique() is applied

In [5]:
WDI_df.groupby('Country Code').count()['Indicator Name'].unique()

array([1599], dtype=int64)

The only value in this column is '1599', hence this is the number of indicators for each country.

In [6]:
WDI_df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', 'Unnamed: 63'],
      dtype='object')

In [7]:
#Save a new dataframe dropping 'Country Code' and 'Unnamed: 63'

working_df = WDI_df[(WDI_df.columns[0]+','+WDI_df.columns[2]+','+','.join(WDI_df.columns[4:-1])).split(',')]

In [8]:
#Print time it takes to complete this cell of code
#https://thispointer.com/python-how-to-get-current-date-and-time-or-timestamp/

dateTimeObj = datetime.now()
print(dateTimeObj)

countries = working_df['Country Name'].unique()

data = pd.DataFrame(columns=list(working_df['Indicator Name'].unique()))


#Process the working Data Frame by transposing it by country and have the indicators become columns and have the rows by country and year

for country in countries:

    test_df = working_df[working_df['Country Name'] == country]
    test2 = test_df[test_df.columns[1:]].T

    new_columns = list(test2.iloc[0].values)
    old_columns = test2.columns
    mapping = dict(zip(old_columns, new_columns)) 

    test2 = test2.iloc[1:]
    test2.rename(columns=mapping, inplace = True)
    
    #https://www.geeksforgeeks.org/python-convert-two-lists-into-a-dictionary/
    
    mapping2 = dict(zip(list(test2.index), list(map(lambda item: country+"_"+str(item),list(test2.index))))) 
    mapping2

    test2.rename(index=mapping2, inplace = True)
    data = pd.concat([data,test2], sort = False)

    dateTimeObj = datetime.now()
    print(dateTimeObj)
    print(country)

dateTimeObj2 = datetime.now()    
print(dateTimeObj2)

2019-12-09 22:55:37.966509
2019-12-09 22:55:38.180687
Arab World
2019-12-09 22:55:38.256590
Caribbean small states
2019-12-09 22:55:38.322587
Central Europe and the Baltics
2019-12-09 22:55:38.389588
Early-demographic dividend
2019-12-09 22:55:38.447267
East Asia & Pacific
2019-12-09 22:55:38.525397
East Asia & Pacific (excluding high income)
2019-12-09 22:55:38.603528
East Asia & Pacific (IDA & IBRD countries)
2019-12-09 22:55:38.681659
Euro area
2019-12-09 22:55:38.761609
Europe & Central Asia
2019-12-09 22:55:38.838608
Europe & Central Asia (excluding high income)
2019-12-09 22:55:38.917608
Europe & Central Asia (IDA & IBRD countries)
2019-12-09 22:55:38.991055
European Union
2019-12-09 22:55:39.069154
Fragile and conflict affected situations
2019-12-09 22:55:39.169064
Heavily indebted poor countries (HIPC)
2019-12-09 22:55:39.263067
High income
2019-12-09 22:55:39.356031
IBRD only
2019-12-09 22:55:39.444492
IDA & IBRD total
2019-12-09 22:55:39.544014
IDA blend
2019-12-09 22:55:39.629444
IDA only
2019-12-09 22:55:39.740893
IDA total
2019-12-09 22:55:39.843893
Late-demographic dividend
2019-12-09 22:55:39.949855
Latin America & Caribbean
2019-12-09 22:55:40.089893
Latin America & Caribbean (excluding high income)
2019-12-09 22:55:40.238851
Latin America & the Caribbean (IDA & IBRD countries)
2019-12-09 22:55:40.344939
Least developed countries: UN classification
2019-12-09 22:55:40.469935
Low & middle income
2019-12-09 22:55:40.600074
Low income
2019-12-09 22:55:40.724988
Lower middle income
2019-12-09 22:55:40.849991
Middle East & North Africa
2019-12-09 22:55:40.974977
Middle East & North Africa (excluding high income)
2019-12-09 22:55:41.123755
Middle East & North Africa (IDA & IBRD countries)
2019-12-09 22:55:41.260840
Middle income
2019-12-09 22:55:41.401467
North America
2019-12-09 22:55:41.564534
Not classified
2019-12-09 22:55:41.710581
OECD members
2019-12-09 22:55:41.854582
Other small states
2019-12-09 22:55:42.015573
Pacific island small states
2019-12-09 22:55:42.167465
Post-demographic dividend
2019-12-09 22:55:42.323714
Pre-demographic dividend
2019-12-09 22:55:42.479965
Small states
2019-12-09 22:55:42.657340
South Asia
2019-12-09 22:55:42.835559
South Asia (IDA & IBRD)
2019-12-09 22:55:43.015552
Sub-Saharan Africa
2019-12-09 22:55:43.191553
Sub-Saharan Africa (excluding high income)
2019-12-09 22:55:43.371561
Sub-Saharan Africa (IDA & IBRD countries)
2019-12-09 22:55:43.550603
Upper middle income
2019-12-09 22:55:43.738601
World
2019-12-09 22:55:43.926601
Afghanistan
2019-12-09 22:55:44.118600
Albania
2019-12-09 22:55:44.314603
Algeria
2019-12-09 22:55:44.512558
American Samoa
2019-12-09 22:55:44.716601
Andorra
2019-12-09 22:55:44.928601
Angola
2019-12-09 22:55:45.137601
Antigua and Barbuda
2019-12-09 22:55:45.375557
Argentina
2019-12-09 22:55:45.720558
Armenia
2019-12-09 22:55:46.008240
Aruba
2019-12-09 22:55:46.236730
Australia
2019-12-09 22:55:46.454576
Austria
2019-12-09 22:55:46.673313
Azerbaijan
2019-12-09 22:55:46.890737
Bahamas, The
2019-12-09 22:55:47.109442
Bahrain
2019-12-09 22:55:47.328239
Bangladesh
2019-12-09 22:55:47.562613
Barbados
2019-12-09 22:55:47.781376
Belarus
2019-12-09 22:55:48.028795
Belgium
2019-12-09 22:55:48.256748
Belize
2019-12-09 22:55:48.508175
Benin
2019-12-09 22:55:48.733892
Bermuda
2019-12-09 22:55:48.997337
Bhutan
2019-12-09 22:55:49.240475
Bolivia
2019-12-09 22:55:49.503305
Bosnia and Herzegovina
2019-12-09 22:55:49.764572
Botswana
2019-12-09 22:55:50.054239
Brazil
2019-12-09 22:55:50.315672
British Virgin Islands
2019-12-09 22:55:50.643766
Brunei Darussalam
2019-12-09 22:55:50.935288
Bulgaria
2019-12-09 22:55:51.212498
Burkina Faso
2019-12-09 22:55:51.493733
Burundi
2019-12-09 22:55:51.774928
Cabo Verde
2019-12-09 22:55:52.057618
Cambodia
2019-12-09 22:55:52.332582
Cameroon
2019-12-09 22:55:52.629437
Canada
2019-12-09 22:55:52.929276
Cayman Islands
2019-12-09 22:55:53.203857
Central African Republic
2019-12-09 22:55:53.500728
Chad
2019-12-09 22:55:53.797608
Channel Islands
2019-12-09 22:55:54.105275
Chile
2019-12-09 22:55:54.402162
China
2019-12-09 22:55:54.714649
Colombia
2019-12-09 22:55:55.070294
Comoros
2019-12-09 22:55:55.409365
Congo, Dem. Rep.
2019-12-09 22:55:55.760598
Congo, Rep.
2019-12-09 22:55:56.123252
Costa Rica
2019-12-09 22:55:56.475899
Cote d'Ivoire
2019-12-09 22:55:56.804082
Croatia
2019-12-09 22:55:57.147037
Cuba
2019-12-09 22:55:57.469092
Curacao
2019-12-09 22:55:57.797149
Cyprus
2019-12-09 22:55:58.148992
Czech Republic
2019-12-09 22:55:58.487685
Denmark
2019-12-09 22:55:58.831426
Djibouti
2019-12-09 22:55:59.186604
Dominica
2019-12-09 22:55:59.539943
Dominican Republic
2019-12-09 22:55:59.899329
Ecuador
2019-12-09 22:56:00.251585
Egypt, Arab Rep.
2019-12-09 22:56:00.604570
El Salvador
2019-12-09 22:56:00.976874
Equatorial Guinea
2019-12-09 22:56:01.334603
Eritrea
2019-12-09 22:56:01.687227
Estonia
2019-12-09 22:56:02.078506
Eswatini
2019-12-09 22:56:02.487770
Ethiopia
2019-12-09 22:56:02.894071
Faroe Islands
2019-12-09 22:56:03.332351
Fiji
2019-12-09 22:56:03.710961
Finland
2019-12-09 22:56:04.133203
France
2019-12-09 22:56:04.517743
French Polynesia
2019-12-09 22:56:04.892744
Gabon
2019-12-09 22:56:05.304081
Gambia, The
2019-12-09 22:56:05.690855
Georgia
2019-12-09 22:56:06.094661
Germany
2019-12-09 22:56:06.494246
Ghana
2019-12-09 22:56:06.900494
Gibraltar
2019-12-09 22:56:07.327190
Greece
2019-12-09 22:56:07.727873
Greenland
2019-12-09 22:56:08.170028
Grenada
2019-12-09 22:56:08.622584
Guam
2019-12-09 22:56:09.104201
Guatemala
2019-12-09 22:56:09.561057
Guinea
2019-12-09 22:56:09.998583
Guinea-Bissau
2019-12-09 22:56:10.449753
Guyana
2019-12-09 22:56:10.897008
Haiti
2019-12-09 22:56:11.376272
Honduras
2019-12-09 22:56:11.880015
Hong Kong SAR, China
2019-12-09 22:56:12.379413
Hungary
2019-12-09 22:56:12.846256
Iceland
2019-12-09 22:56:13.284258
India
2019-12-09 22:56:13.731618
Indonesia
2019-12-09 22:56:14.195189
Iran, Islamic Rep.
2019-12-09 22:56:14.657952
Iraq
2019-12-09 22:56:15.142431
Ireland
2019-12-09 22:56:15.598670
Isle of Man
2019-12-09 22:56:16.079270
Israel
2019-12-09 22:56:16.542963
Italy
2019-12-09 22:56:17.027346
Jamaica
2019-12-09 22:56:17.505283
Japan
2019-12-09 22:56:17.983932
Jordan
2019-12-09 22:56:18.470549
Kazakhstan
2019-12-09 22:56:18.973976
Kenya
2019-12-09 22:56:19.517976
Kiribati
2019-12-09 22:56:20.011709
Korea, Dem. Peopleâ€™s Rep.
2019-12-09 22:56:20.545857
Korea, Rep.
2019-12-09 22:56:21.073828
Kosovo
2019-12-09 22:56:21.606252
Kuwait
2019-12-09 22:56:22.111254
Kyrgyz Republic
2019-12-09 22:56:22.620691
Lao PDR
2019-12-09 22:56:23.139889
Latvia
2019-12-09 22:56:23.774700
Lebanon
2019-12-09 22:56:24.345616
Lesotho
2019-12-09 22:56:24.917901
Liberia
2019-12-09 22:56:25.468289
Libya
2019-12-09 22:56:25.994005
Liechtenstein
2019-12-09 22:56:26.553848
Lithuania
2019-12-09 22:56:27.094325
Luxembourg
2019-12-09 22:56:27.637579
Macao SAR, China
2019-12-09 22:56:28.187463
Madagascar
2019-12-09 22:56:28.727988
Malawi
2019-12-09 22:56:29.303443
Malaysia
2019-12-09 22:56:29.843957
Maldives
2019-12-09 22:56:30.419609
Mali
2019-12-09 22:56:30.976161
Malta
2019-12-09 22:56:31.534273
Marshall Islands
2019-12-09 22:56:32.106244
Mauritania
2019-12-09 22:56:32.669023
Mauritius
2019-12-09 22:56:33.238791
Mexico
2019-12-09 22:56:33.811425
Micronesia, Fed. Sts.
2019-12-09 22:56:34.399164
Moldova
2019-12-09 22:56:34.987779
Monaco
2019-12-09 22:56:35.601532
Mongolia
2019-12-09 22:56:36.199239
Montenegro
2019-12-09 22:56:36.793748
Morocco
2019-12-09 22:56:37.413333
Mozambique
2019-12-09 22:56:38.001395
Myanmar
2019-12-09 22:56:38.597106
Namibia
2019-12-09 22:56:39.200559
Nauru
2019-12-09 22:56:39.797408
Nepal
2019-12-09 22:56:40.417842
Netherlands
2019-12-09 22:56:41.099177
New Caledonia
2019-12-09 22:56:41.793690
New Zealand
2019-12-09 22:56:42.473893
Nicaragua
2019-12-09 22:56:43.092943
Niger
2019-12-09 22:56:43.780837
Nigeria
2019-12-09 22:56:44.462950
North Macedonia
2019-12-09 22:56:45.117843
Northern Mariana Islands
2019-12-09 22:56:45.777864
Norway
2019-12-09 22:56:46.450573
Oman
2019-12-09 22:56:47.153584
Pakistan
2019-12-09 22:56:47.857203
Palau
2019-12-09 22:56:48.618744
Panama
2019-12-09 22:56:49.344377
Papua New Guinea
2019-12-09 22:56:50.041525
Paraguay

2019-12-09 22:56:51.014457
Peru
2019-12-09 22:56:51.826452
Philippines
2019-12-09 22:56:52.529783
Poland
2019-12-09 22:56:53.227199
Portugal
2019-12-09 22:56:53.934343
Puerto Rico
2019-12-09 22:56:54.637338
Qatar
2019-12-09 22:56:55.369756
Romania
2019-12-09 22:56:56.137695
Russian Federation
2019-12-09 22:56:56.900601
Rwanda
2019-12-09 22:56:57.706425
Samoa
2019-12-09 22:56:58.533427
San Marino
2019-12-09 22:56:59.356395
Sao Tome and Principe
2019-12-09 22:57:00.171439
Saudi Arabia
2019-12-09 22:57:00.930439
Senegal
2019-12-09 22:57:01.675437
Serbia
2019-12-09 22:57:02.493438
Seychelles
2019-12-09 22:57:03.642352
Sierra Leone
2019-12-09 22:57:04.457986
Singapore
2019-12-09 22:57:05.270477
Sint Maarten (Dutch part)
2019-12-09 22:57:06.059761
Slovak Republic
2019-12-09 22:57:06.841368
Slovenia
2019-12-09 22:57:07.622283
Solomon Islands
2019-12-09 22:57:08.414685
Somalia
2019-12-09 22:57:09.167469
South Africa
2019-12-09 22:57:09.965668
South Sudan
2019-12-09 22:57:10.949407
Spain
2019-12-09 22:57:11.926772
Sri Lanka
2019-12-09 22:57:12.795781
St. Kitts and Nevis
2019-12-09 22:57:13.797590
St. Lucia
2019-12-09 22:57:14.668772
St. Martin (French part)
2019-12-09 22:57:15.566789
St. Vincent and the Grenadines
2019-12-09 22:57:16.462127
Sudan
2019-12-09 22:57:17.303383
Suriname
2019-12-09 22:57:18.204597
Sweden
2019-12-09 22:57:19.141901
Switzerland
2019-12-09 22:57:20.034512
Syrian Arab Republic
2019-12-09 22:57:21.040132
Tajikistan
2019-12-09 22:57:22.115541
Tanzania
2019-12-09 22:57:23.135261
Thailand
2019-12-09 22:57:24.162152
Timor-Leste
2019-12-09 22:57:25.076046
Togo
2019-12-09 22:57:26.096516
Tonga
2019-12-09 22:57:27.177316
Trinidad and Tobago
2019-12-09 22:57:28.137826
Tunisia
2019-12-09 22:57:29.099593
Turkey
2019-12-09 22:57:30.026396
Turkmenistan
2019-12-09 22:57:30.999128
Turks and Caicos Islands
2019-12-09 22:57:31.913287
Tuvalu
2019-12-09 22:57:32.809929
Uganda
2019-12-09 22:57:33.700117
Ukraine
2019-12-09 22:57:35.042419
United Arab Emirates
2019-12-09 22:57:36.293378
United Kingdom
2019-12-09 22:57:37.353320
United States
2019-12-09 22:57:38.447294
Uruguay
2019-12-09 22:57:39.362555
Uzbekistan
2019-12-09 22:57:40.263198
Vanuatu
2019-12-09 22:57:41.367450
Venezuela, RB
2019-12-09 22:57:42.475909
Vietnam
2019-12-09 22:57:43.686305
Virgin Islands (U.S.)
2019-12-09 22:57:44.767865
West Bank and Gaza
2019-12-09 22:57:45.710580
Yemen, Rep.
2019-12-09 22:57:46.883954
Zambia
2019-12-09 22:57:47.932027
Zimbabwe
2019-12-09 22:57:47.932027

In [9]:
data

,"2005 PPP conversion factor, GDP (LCU per international $)","2005 PPP conversion factor, private consumption (LCU per international $)",Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+),"Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)",...,"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)",Women who believe a husband is justified in beating his wife (any of five reasons) (%),Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%)
Arab World_1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World_1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe_1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe_1990,NaN,NaN,NaN,30.3578,7.83181,85.5399,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.2
Zimbabwe_1991,NaN,NaN,NaN,30.7188,7.51522,85.5419,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.9
Zimbabwe_1992,NaN,NaN,NaN,28.2,3.03592,85.5438,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.5
Zimbabwe_1993,NaN,NaN,NaN,31.4367,7.19543,85.5446,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53
Zimbabwe_1994,NaN,NaN,NaN,28.1,3.4,80.4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.4,31,53.4
Zimbabwe_1995,NaN,NaN,NaN,32.1301,7.30475,85.5391,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.7
Zimbabwe_1996,NaN,NaN,NaN,32.4599,7.33369,85.5307,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54
Zimbabwe_1997,NaN,NaN,NaN,32.7745,7.34058,85.5171,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.3
Zimbabwe_1998,NaN,NaN,NaN,33.0708,7.31988,85.4973,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.6
Zimbabwe_1999,NaN,NaN,NaN,38.4,8.3,87.4,NaN,NaN,NaN,NaN,...,40.5,51,31.7,12,27.8,31.2,22.3,4.6,28.7,54.9
Zimbabwe_2000,NaN,NaN,32.4,33.5974,7.17977,85.4358,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.3
Zimbabwe_2001,NaN,NaN,32.25,33.8309,7.06538,85.3957,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.6
Zimbabwe_2002,NaN,NaN,32.18,34.2,7.15528,85.3531,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.9
Zimbabwe_2003,NaN,NaN,32.01,34.2668,7.40605,85.3107,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.2
Zimbabwe_2004,NaN,NaN,31.77,34.4814,7.97256,85.2713,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.5
Zimbabwe_2005,NaN,NaN,31.64,34.7018,8.54036,85.2377,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.8
Zimbabwe_2006,NaN,NaN,31.34,37.2,8.7,91.4,NaN,NaN,NaN,NaN,...,74.9,47.7,26,12.2,33,30.2,24.3,4.6,33.6,57
Zimbabwe_2007,NaN,NaN,31.17,35.1845,9.71319,85.1993,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.2
Zimbabwe_2008,NaN,NaN,30.97,35.4573,10.3317,85.1994,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.4
Zimbabwe_2009,NaN,NaN,30.81,43.3691,17.4528,90.8619,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.1,57.4
Zimbabwe_2010,NaN,NaN,30.46,36.0631,11.6286,85.2352,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.2
Zimbabwe_2011,NaN,NaN,30.27,36.9,13.3,83.2,39.6512,37.1244,42.5456,50.0355,...,74.5,39.6,15.6,7.5,22.3,21.4,16.9,3.9,30.5,58.4
Zimbabwe_2012,NaN,NaN,30.02,36.7289,12.9816,85.3068,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.6
Zimbabwe_2013,NaN,NaN,29.88,37.0768,13.6699,85.3515,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.8
Zimbabwe_2014,NaN,NaN,29.63,32.3,9.8,83.4,32.3893,28.9797,35.9539,36.8856,...,NaN,37.4,NaN,NaN,NaN,NaN,NaN,NaN,33.5,58.9
Zimbabwe_2015,NaN,NaN,29.36,33.7,9.7,81.2,NaN,NaN,NaN,NaN,...,72.1,38.7,16.7,8.1,22.8,21.4,14.5,3.7,32.4,58.9
Zimbabwe_2016,NaN,NaN,29.05,38.1451,15.5756,85.5002,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59
Zimbabwe_2017,NaN,NaN,NaN,NaN,NaN,NaN,55.2851,51.6649,59.2275,58.8771,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.1
Zimbabwe_2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 15576 entries, Arab World_1960 to Zimbabwe_2018
Data columns (total 1599 columns):
2005 PPP conversion factor, GDP (LCU per international $)                                                                                       184 non-null object
2005 PPP conversion factor, private consumption (LCU per international $)                                                                       184 non-null object
Access to clean fuels and technologies for cooking (% of population)                                                                            3995 non-null object
Access to electricity (% of population)                                                                                                         6958 non-null object
Access to electricity, rural (% of rural population)                                                                                            6271 non-null object
Access to electricity, urban (% of urban population)                                                                                            6959 non-null object
Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+)                                 491 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)                         491 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)                           491 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)                   491 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)                    482 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)      490 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)                    482 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)    490 non-null object
Account ownership at a financial institution or with a mobile-money-service provider, young adults (% of population ages 15-24)                 491 non-null object
Adequacy of social insurance programs (% of total welfare of beneficiary households)                                                            263 non-null object
Adequacy of social protection and labor programs (% of total welfare of beneficiary households)                                                 281 non-null object
Adequacy of social safety net programs (% of total welfare of beneficiary households)                                                           247 non-null object
Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households)                                                       81 non-null object
Adjusted net enrollment rate, primary (% of primary school age children)                                                                        6121 non-null object
Adjusted net enrollment rate, primary, female (% of primary school age children)                                                                5504 non-null object
Adjusted net enrollment rate, primary, male (% of primary school age children)                                                                  5503 non-null object
Adjusted net national income (annual % growth)                                                                                                  6117 non-null object
Adjusted net national income (constant 2010 US$)                                                                                                6147 non-null object
Adjusted net national income (current US$)                                                                                                      8549 non-null object
Adjusted net national income per capita (annual % growth)                                                                                       6117 non-null object
Adjusted net national income per capita (constant 2010 US$)                                                                                     6147 non-null object
Adjusted net national income per capita (current US$)                                                                                           8546 non-null object
Adjusted net savings, excluding particulate emission damage (% of GNI)                                                                          6553 non-null object
Adjusted net savings, excluding particulate emission damage (current US$)                                                                       4914 non-null object
Adjusted net savings, including particulate emission damage (% of GNI)                                                                          4725 non-null object
Adjusted net savings, including particulate emission damage (current US$)                                                                       3574 non-null object
Adjusted savings: carbon dioxide damage (% of GNI)                                                                                              9854 non-null object
Adjusted savings: carbon dioxide damage (current US$)                                                                                           9058 non-null object
Adjusted savings: consumption of fixed capital (% of GNI)                                                                                       9876 non-null object
Adjusted savings: consumption of fixed capital (current US$)                                                                                    8136 non-null object
Adjusted savings: education expenditure (% of GNI)                                                                                              11606 non-null object
Adjusted savings: education expenditure (current US$)                                                                                           7627 non-null object
Adjusted savings: energy depletion (% of GNI)                                                                                                   9413 non-null object
Adjusted savings: energy depletion (current US$)                                                                                                8744 non-null object
Adjusted savings: gross savings (% of GNI)                                                                                                      6940 non-null object
Adjusted savings: mineral depletion (% of GNI)                                                                                                  10067 non-null object
Adjusted savings: mineral depletion (current US$)                                                                                               10416 non-null object
Adjusted savings: natural resources depletion (% of GNI)                                                                                        8798 non-null object
Adjusted savings: net forest depletion (% of GNI)                                                                                               9132 non-null object
Adjusted savings: net forest depletion (current US$)                                                                                            8099 non-null object
Adjusted savings: net national savings (% of GNI)                                                                                               6920 non-null object
Adjusted savings: net national savings (current US$)                                                                                            5276 non-null object
Adjusted savings: particulate emission damage (% of GNI)                                                                                        5932 non-null object
Adjusted savings: particulate emission damage (current US$)                                                                                     4788 non-null object
Adolescent fertility rate (births per 1,000 women ages 15-19)                                                                                   13920 non-null object
Adolescents out of school (% of lower secondary school age)                                                                                     3517 non-null object
Adolescents out of school, female (% of female lower secondary school age)                                                                      2921 non-null object
Adolescents out of school, male (% of male lower secondary school age)                                                                          2909 non-null object
Adults (ages 15+) and children (ages 0-14) newly infected with HIV                                                                              3621 non-null object
Adults (ages 15+) newly infected with HIV                                                                                                       3613 non-null object
Age dependency ratio (% of working-age population)                                                                                              13851 non-null object
Age dependency ratio, old (% of working-age population)                                                                                         13851 non-null object
Age dependency ratio, young (% of working-age population)                                                                                       13851 non-null object
Agricultural irrigated land (% of total agricultural land)                                                                                      856 non-null object
Agricultural land (% of land area)                                                                                                              13055 non-null object
Agricultural land (sq. km)                                                                                                                      13232 non-null object
Agricultural machinery, tractors                                                                                                                7783 non-null object
Agricultural machinery, tractors per 100 sq. km of arable land                                                                                  7444 non-null object
Agricultural methane emissions (% of total)                                                                                                     9715 non-null object
Agricultural methane emissions (thousand metric tons of CO2 equivalent)                                                                         10520 non-null object
Agricultural nitrous oxide emissions (% of total)                                                                                               9754 non-null object
Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)                                                                   10520 non-null object
Agricultural raw materials exports (% of merchandise exports)                                                                                   8586 non-null object
Agricultural raw materials imports (% of merchandise imports)                                                                                   8631 non-null object
Agriculture, forestry, and fishing, value added (% of GDP)                                                                                      9341 non-null object
Agriculture, forestry, and fishing, value added (annual % growth)                                                                               8548 non-null object
Agriculture, forestry, and fishing, value added (constant 2010 US$)                                                                             8609 non-null object
Agriculture, forestry, and fishing, value added (constant LCU)                                                                                  6934 non-null object
Agriculture, forestry, and fishing, value added (current LCU)                                                                                   7541 non-null object
Agriculture, forestry, and fishing, value added (current US$)                                                                                   9216 non-null object
Agriculture, forestry, and fishing, value added per worker (constant 2010 US$)                                                                  5268 non-null object
Air transport, freight (million ton-km)                                                                                                         8613 non-null object
Air transport, passengers carried                                                                                                               9010 non-null object
Air transport, registered carrier departures worldwide                                                                                          9003 non-null object
Alternative and nuclear energy (% of total energy use)                                                                                          8137 non-null object
Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)                                                                   565 non-null object
Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)                                                                      578 non-null object
Annual freshwater withdrawals, industry (% of total freshwater withdrawal)                                                                      561 non-null object
Annual freshwater withdrawals, total (% of internal resources)                                                                                  674 non-null object
Annual freshwater withdrawals, total (billion cubic meters)                                                                                     642 non-null object
Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)                               93 non-null object
Annualized average growth rate in per capita real survey mean consumption or income, total population (%)                                       93 non-null object
Antiretroviral therapy coverage (% of people living with HIV)                                                                                   3027 non-null object
Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)                                                                 958 non-null object
Aquaculture production (metric tons)                                                                                                            10880 non-null object
Arable land (% of land area)                                                                                                                    12918 non-null object
Arable land (hectares per person)                                                                                                               12892 non-null object
Arable land (hectares)                                                                                                                          10513 non-null object
ARI treatment (% of children under 5 taken to a health provider)                                                                                468 non-null object
Armed forces personnel (% of total labor force)                                                                                                 5763 non-null object
Armed forces personnel, total                                                                                                                   6172 non-null object
Arms exports (SIPRI trend indicator values)                                                                                                     2929 non-null object
Arms imports (SIPRI trend indicator values)                                                                                                     8253 non-null object
Automated teller machines (ATMs) (per 100,000 adults)                                                                                           2880 non-null object
Average grace period on new external debt commitments (years)                                                                                   6525 non-null object
Average grace period on new external debt commitments, official (years)                                                                         6525 non-null object
Average grace period on new external debt commitments, private (years)                                                                          6525 non-null object
Average grant element on new external debt commitments (%)                                                                                      6525 non-null object
Average grant element on new external debt commitments, official (%)                                                                            6525 non-null object
Average grant element on new external debt commitments, private (%)                                                                             6525 non-null object
Average interest on new external debt commitments (%)                                                                                           6525 non-null object
Average interest on new external debt commitments, official (%)                                                                                 6525 non-null object
Average interest on new external debt commitments, private (%)                                                                                  6525 non-null object
Average maturity on new external debt commitments (years)                                                                                       6525 non-null object
Average maturity on new external debt commitments, official (years)                                                                             6525 non-null object
Average maturity on new external debt commitments, private (years)                                                                              6525 non-null object
Average precipitation in depth (mm per year)                                                                                                    2068 non-null object
Average time to clear exports through customs (days)                                                                                            355 non-null object
Average transaction cost of sending remittances from a specific country (%)                                                                     253 non-null object
Average transaction cost of sending remittances to a specific country (%)                                                                       650 non-null object
Average working hours of children, study and work, ages 7-14 (hours per week)                                                                   132 non-null object
Average working hours of children, study and work, female, ages 7-14 (hours per week)                                                           132 non-null object
Average working hours of children, study and work, male, ages 7-14 (hours per week)                                                             132 non-null object
Average working hours of children, working only, ages 7-14 (hours per week)                                                                     126 non-null object

Data Frame was successfully transposed with the intended rows. This structure will be more useful for the machine learning parts of this project.

In [11]:
#Count and display the number of null values in the Data Frame
data_null = pd.DataFrame(data.isna().sum())
data_null

                                                        0
2005 PPP conversion factor, GDP (LCU per intern...  15392
2005 PPP conversion factor, private consumption...  15392
Access to clean fuels and technologies for cook...  11581
Access to electricity (% of population)              8618
Access to electricity, rural (% of rural popula...   9305
Access to electricity, urban (% of urban popula...   8617
Account ownership at a financial institution or...  15085
Account ownership at a financial institution or...  15085
Account ownership at a financial institution or...  15085
Account ownership at a financial institution or...  15085
Account ownership at a financial institution or...  15094
Account ownership at a financial institution or...  15086
Account ownership at a financial institution or...  15094
Account ownership at a financial institution or...  15086
Account ownership at a financial institution or...  15085
Adequacy of social insurance programs (% of tot...  15313
Adequacy of social protection and labor program...  15295
Adequacy of social safety net programs (% of to...  15329
Adequacy of unemployment benefits and ALMP (% o...  15495
Adjusted net enrollment rate, primary (% of pri...   9455
Adjusted net enrollment rate, primary, female (...  10072
Adjusted net enrollment rate, primary, male (% ...  10073
Adjusted net national income (annual % growth)       9459
Adjusted net national income (constant 2010 US$)     9429
Adjusted net national income (current US$)           7027
Adjusted net national income per capita (annual...   9459
Adjusted net national income per capita (consta...   9429
Adjusted net national income per capita (curren...   7030
Adjusted net savings, excluding particulate emi...   9023
Adjusted net savings, excluding particulate emi...  10662
...                                                   ...
Urban population                                      545
Urban population (% of total)                         504
Urban population growth (annual %)                    595
Urban population living in areas where elevatio...  14901
Urban poverty gap at national poverty lines (%)     15382
Urban poverty headcount ratio at national pover...  15249
Use of IMF credit (DOD, current US$)                 9165
Use of insecticide-treated bed nets (% of under...  15330
Value lost due to electrical outages (% of sale...  15288
Vitamin A supplementation coverage rate (% of c...  14289
Vulnerable employment, female (% of female empl...   9052
Vulnerable employment, male (% of male employme...   9052
Vulnerable employment, total (% of total employ...   9052
Wage and salaried workers, female (% of female ...   9052
Wage and salaried workers, male (% of male empl...   9052
Wage and salaried workers, total (% of total em...   9052
Wanted fertility rate (births per woman)            15263
Water productivity, total (constant 2010 US$ GD...  13886
Wholesale price index (2010 = 100)                  14218
Women making their own informed decisions regar...  15509
Women participating in the three decisions (own...  15436
Women who believe a husband is justified in bea...  15360
Women who believe a husband is justified in bea...  15412
Women who believe a husband is justified in bea...  15414
Women who believe a husband is justified in bea...  15411
Women who believe a husband is justified in bea...  15410
Women who believe a husband is justified in bea...  15413
Women who were first married by age 15 (% of wo...  15207
Women who were first married by age 18 (% of wo...  15119
Women's share of population ages 15+ living wit...  10990

[1599 rows x 1 columns]

In [12]:
data_null[0].max()

#At least one column (year) is completely empty.

15576

In order to apply machine learning, only those columns with <80% null values will be kept in the Data Frame

In [13]:
data_wo_null_columns = data[list(filter(lambda x: sum(data[x].isna())/len(data) < 0.8, data.columns))]
len(data_wo_null_columns.columns)

1044

There number of features went from 1599 to 1044 by eliminating these columns. Of course the <80% is an arbitrary criteria but does allow for establishing a code with a variable rule for dropping columns given a threshold.

As a next step, rows with null values will be dropped.

In [14]:
data_wo_null_columns.dropna(how = 'any', inplace = False)

Empty DataFrame
Columns: [Access to clean fuels and technologies for cooking (% of population), Access to electricity (% of population), Access to electricity, rural (% of rural population), Access to electricity, urban (% of urban population), Adjusted net enrollment rate, primary (% of primary school age children), Adjusted net enrollment rate, primary, female (% of primary school age children), Adjusted net enrollment rate, primary, male (% of primary school age children), Adjusted net national income (annual % growth), Adjusted net national income (constant 2010 US$), Adjusted net national income (current US$), Adjusted net national income per capita (annual % growth), Adjusted net national income per capita (constant 2010 US$), Adjusted net national income per capita (current US$), Adjusted net savings, excluding particulate emission damage (% of GNI), Adjusted net savings, excluding particulate emission damage (current US$), Adjusted net savings, including particulate emission damage (% of GNI), Adjusted net savings, including particulate emission damage (current US$), Adjusted savings: carbon dioxide damage (% of GNI), Adjusted savings: carbon dioxide damage (current US$), Adjusted savings: consumption of fixed capital (% of GNI), Adjusted savings: consumption of fixed capital (current US$), Adjusted savings: education expenditure (% of GNI), Adjusted savings: education expenditure (current US$), Adjusted savings: energy depletion (% of GNI), Adjusted savings: energy depletion (current US$), Adjusted savings: gross savings (% of GNI), Adjusted savings: mineral depletion (% of GNI), Adjusted savings: mineral depletion (current US$), Adjusted savings: natural resources depletion (% of GNI), Adjusted savings: net forest depletion (% of GNI), Adjusted savings: net forest depletion (current US$), Adjusted savings: net national savings (% of GNI), Adjusted savings: net national savings (current US$), Adjusted savings: particulate emission damage (% of GNI), Adjusted savings: particulate emission damage (current US$), Adolescent fertility rate (births per 1,000 women ages 15-19), Adolescents out of school (% of lower secondary school age), Adults (ages 15+) and children (ages 0-14) newly infected with HIV, Adults (ages 15+) newly infected with HIV, Age dependency ratio (% of working-age population), Age dependency ratio, old (% of working-age population), Age dependency ratio, young (% of working-age population), Agricultural land (% of land area), Agricultural land (sq. km), Agricultural machinery, tractors, Agricultural machinery, tractors per 100 sq. km of arable land, Agricultural methane emissions (% of total), Agricultural methane emissions (thousand metric tons of CO2 equivalent), Agricultural nitrous oxide emissions (% of total), Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent), Agricultural raw materials exports (% of merchandise exports), Agricultural raw materials imports (% of merchandise imports), Agriculture, forestry, and fishing, value added (% of GDP), Agriculture, forestry, and fishing, value added (annual % growth), Agriculture, forestry, and fishing, value added (constant 2010 US$), Agriculture, forestry, and fishing, value added (constant LCU), Agriculture, forestry, and fishing, value added (current LCU), Agriculture, forestry, and fishing, value added (current US$), Agriculture, forestry, and fishing, value added per worker (constant 2010 US$), Air transport, freight (million ton-km), Air transport, passengers carried, Air transport, registered carrier departures worldwide, Alternative and nuclear energy (% of total energy use), Aquaculture production (metric tons), Arable land (% of land area), Arable land (hectares per person), Arable land (hectares), Armed forces personnel (% of total labor force), Armed forces personnel, total, Arms imports (SIPRI trend indicator values), Average grace period on new external debt commitments (years), Average grace period on new external debt commitments, official (years), Average grace period on new external debt commitments, private (years), Average grant element on new external debt commitments (%), Average grant element on new external debt commitments, official (%), Average grant element on new external debt commitments, private (%), Average interest on new external debt commitments (%), Average interest on new external debt commitments, official (%), Average interest on new external debt commitments, private (%), Average maturity on new external debt commitments (years), Average maturity on new external debt commitments, official (years), Average maturity on new external debt commitments, private (years), Binding coverage, all products (%), Birth rate, crude (per 1,000 people), Broad money (% of GDP), Broad money (current LCU), Broad money growth (annual %), Broad money to total reserves ratio, Business extent of disclosure index (0=less disclosure to 10=more disclosure), Capture fisheries production (metric tons), Cereal production (metric tons), Cereal yield (kg per hectare), Changes in inventories (constant LCU), Changes in inventories (current LCU), Changes in inventories (current US$), Charges for the use of intellectual property, payments (BoP, current US$), Charges for the use of intellectual property, receipts (BoP, current US$), Chemicals (% of value added in manufacturing), Children out of school (% of primary school age), Children out of school, female (% of female primary school age), ...]
Index: []

[0 rows x 1044 columns]

This shows that in every row, there is at least one null value, even with the 'full null columns' that were previously dropped.

A new approach will be introduced by using a threshold, in which the row should have at least a given number of non-null values not to be dropped from the Data Frame.

In [15]:
threshold = 0.35
data_wo_null_columns.dropna(how = 'any', inplace = False, thresh=(1044-(threshold*1044)))

,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)","Adjusted net enrollment rate, primary (% of primary school age children)","Adjusted net enrollment rate, primary, female (% of primary school age children)","Adjusted net enrollment rate, primary, male (% of primary school age children)",Adjusted net national income (annual % growth),Adjusted net national income (constant 2010 US$),Adjusted net national income (current US$),...,Urban population (% of total),Urban population growth (annual %),"Use of IMF credit (DOD, current US$)","Vulnerable employment, female (% of female employment) (modeled ILO estimate)","Vulnerable employment, male (% of male employment) (modeled ILO estimate)","Vulnerable employment, total (% of total employment) (modeled ILO estimate)","Wage and salaried workers, female (% of female employment) (modeled ILO estimate)","Wage and salaried workers, male (% of male employment) (modeled ILO estimate)","Wage and salaried workers, total (% of total employment) (modeled ILO estimate)",Women's share of population ages 15+ living with HIV (%)
East Asia & Pacific (excluding high income)_1991,NaN,81.6017,77.7622,93.7392,95.0922,92.6258,97.4391,NaN,NaN,6.18612e+11,...,28.8826,4.32874,1.47895e+09,72.6379,62.2539,66.8624,26.4816,34.3785,30.874,NaN
East Asia & Pacific (excluding high income)_1992,NaN,83.8894,80.3456,94.521,94.2848,91.9763,96.4804,NaN,NaN,6.96887e+11,...,29.6838,4.22073,1.31942e+09,71.7326,61.3508,65.9655,27.3479,35.2299,31.7265,NaN
East Asia & Pacific (excluding high income)_1993,NaN,83.246,79.1646,94.5561,93.3924,91.2315,95.4464,NaN,NaN,7.64378e+11,...,30.4978,4.11576,1.42987e+09,70.6966,60.3645,64.9552,28.3634,36.213,32.7252,NaN
East Asia & Pacific (excluding high income)_1994,NaN,84.5359,81.0849,95.1208,92.4523,90.3842,94.4168,NaN,NaN,9.22501e+11,...,31.3257,4.05902,1.4934e+09,69.8357,59.5888,64.1385,29.2001,36.9823,33.5266,NaN
East Asia & Pacific (excluding high income)_1995,NaN,85.46,81.5517,95.1957,91.2816,89.4251,93.0431,NaN,2.66254e+12,1.12614e+12,...,32.1665,3.983,1.33671e+09,68.9374,58.7446,63.2693,30.0562,37.7589,34.3388,NaN
East Asia & Pacific (excluding high income)_1996,NaN,86.5758,82.9203,95.4349,90.6572,89.1614,92.0745,-12.7135,2.32404e+12,1.2848e+12,...,33.0225,3.91874,1.17482e+09,68.0397,57.9434,62.4264,30.9323,38.554,35.1697,NaN
East Asia & Pacific (excluding high income)_1997,NaN,87.7491,84.6904,96.0664,90.246,88.9817,91.442,1.33232,2.355e+12,1.33077e+12,...,33.8874,3.84591,6.93295e+09,67.1538,57.2561,61.6515,31.8152,39.2724,35.961,NaN
East Asia & Pacific (excluding high income)_1998,NaN,88.5038,84.5261,96.0052,92.3512,91.5504,93.1068,-21.507,1.84851e+12,1.20346e+12,...,34.7653,3.75811,1.45109e+10,66.5621,57.0164,61.2553,32.3791,39.4856,36.3302,NaN
East Asia & Pacific (excluding high income)_1999,NaN,89.1837,85.3034,96.1344,94.3608,93.9825,94.7168,-1.15889,1.82709e+12,1.32237e+12,...,35.6547,3.64537,1.72658e+10,65.7822,56.3985,60.5661,33.0853,39.931,36.8904,NaN
East Asia & Pacific (excluding high income)_2000,39.1937,89.7265,86.3458,96.4544,94.7173,94.3352,95.0752,-2.64388,1.77878e+12,1.44222e+12,...,36.5688,3.58332,1.76001e+10,65.0359,55.7338,59.8685,33.8166,40.6239,37.5987,NaN
East Asia & Pacific (excluding high income)_2001,40.3488,90.289,86.5471,96.484,95.1813,94.8406,95.4989,3.72439,1.84503e+12,1.51036e+12,...,37.5976,3.78011,1.44925e+10,64.0383,54.5289,58.7388,34.8031,41.6589,38.6237,NaN
East Asia & Pacific (excluding high income)_2002,41.2262,90.8779,87.2283,96.6881,97.3966,97.1523,97.6232,43.0112,2.6386e+12,1.69223e+12,...,38.7066,3.86748,1.28182e+10,63.2614,53.8849,58.0246,35.5517,42.2575,39.2965,NaN
East Asia & Pacific (excluding high income)_2003,42.2912,91.2087,87.6517,97.1556,97.1796,96.8388,97.4941,-11.729,2.32912e+12,1.90537e+12,...,39.8278,3.77001,1.34419e+10,62.3836,53.2869,57.2981,36.4033,42.8651,40.0156,NaN
East Asia & Pacific (excluding high income)_2004,43.1899,91.7333,88.0033,97.0536,97.2095,96.9288,97.4667,27.912,2.97922e+12,2.17011e+12,...,40.9597,3.68437,1.23326e+10,61.1528,52.079,56.0655,37.5959,44.0269,41.2016,NaN
East Asia & Pacific (excluding high income)_2005,44.347,91.9487,88.1274,97.2202,95.062,94.7325,95.3633,6.76432,3.18074e+12,2.47899e+12,...,42.0959,3.60158,9.80671e+09,59.8982,51.1884,55.0086,38.8018,44.9291,42.2422,NaN
East Asia & Pacific (excluding high income)_2006,45.6916,93.0306,89.6665,97.4168,94.5016,94.2089,94.7689,16.1961,3.6959e+12,2.97737e+12,...,43.2075,3.4359,1.56691e+09,58.8829,50.3584,54.0893,39.7727,45.7401,43.129,NaN
East Asia & Pacific (excluding high income)_2007,46.8741,93.1855,89.723,97.6812,95.5669,95.4106,95.7094,27.9213,4.72784e+12,3.73879e+12,...,44.3072,3.30487,1.61239e+09,58.1058,49.5275,53.2866,40.4762,46.5599,43.8937,NaN
East Asia & Pacific (excluding high income)_2008,48.2388,93.8527,90.4103,97.8517,95.6406,95.4664,95.799,4.96809,4.96272e+12,4.60674e+12,...,45.4118,3.24068,1.51956e+09,57.2571,48.8181,52.5132,41.2773,47.2193,44.618,NaN
East Asia & Pacific (excluding high income)_2009,49.5032,94.4316,91.2752,98.0057,96.0271,95.8915,96.15,12.8423,5.60005e+12,5.12034e+12,...,46.5171,3.17069,1.87128e+10,56.3701,48.0313,51.6761,42.0727,47.9036,45.3546,NaN
East Asia & Pacific (excluding high income)_2010,50.8409,94.9973,91.1334,98.1912,96.1975,96.3171,96.0895,8.10959,6.05419e+12,6.05419e+12,...,47.6237,3.10921,1.83905e+10,55.5047,47.3721,50.9185,42.9558,48.6276,46.1544,NaN
East Asia & Pacific (excluding high income)_2011,52.032,95.357,92.4718,98.293,96.4167,96.8324,96.0424,5.27628,6.37363e+12,7.18371e+12,...,48.6657,2.91928,1.82951e+10,54.6327,46.4522,50.0196,43.8096,49.5452,47.0444,NaN
East Asia & Pacific (excluding high income)_2012,53.2364,95.8117,93.2648,98.3633,96.3122,96.4472,96.1909,9.25034,6.96321e+12,8.18631e+12,...,49.6799,2.8237,1.82723e+10,53.7733,45.6238,49.1761,44.6327,50.3578,47.8624,NaN
East Asia & Pacific (excluding high income)_2013,54.4463,96.0572,93.5106,98.4622,95.9891,96.1084,95.8821,6.137,7.39054e+12,8.95237e+12,...,50.6872,2.77036,1.82241e+10,52.9325,44.9303,48.4152,45.4566,51.0465,48.6122,NaN
East Asia & Pacific (excluding high income)_2014,55.4101,96.2182,94.2258,98.5584,96.0956,96.009,96.1731,7.01021,7.90864e+12,9.68118e+12,...,51.6914,2.72543,1.70673e+10,52.1979,44.3426,47.7621,46.1789,51.6249,49.2537,NaN
East Asia & Pacific (excluding high income)_2015,56.4242,96.5332,94.3095,98.7031,96.0152,95.7559,96.2473,7.66813,8.51508e+12,1.0157e+13,...,52.6905,2.66692,1.63628e+10,51.1926,43.3957,46.786,47.1217,52.5294,50.1777,NaN
East Asia & Pacific (excluding high income)_2016,57.3427,96.5807,93.8937,98.8029,95.9467,95.4659,96.3767,7.82093,9.18104e+12,1.04247e+13,...,53.6858,2.63297,1.58666e+10,50.4586,42.9176,46.1964,47.8447,53.0214,50.7714,NaN
East Asia & Pacific (excluding high income)_2017,NaN,NaN,NaN,NaN,95.9865,95.4963,96.4249,5.79287,9.71289e+12,1.11438e+13,...,54.672,2.58139,1.69264e+10,49.8614,42.5255,45.7095,48.4532,53.4594,51.2861,NaN
Europe & Central Asia (excluding high income)_1992,NaN,97.8635,96.1336,98.941,94.5107,93.5879,95.4041,NaN,1.31277e+12,5.19061e+11,...,63.2697,0.554046,2.82005e+09,19.8683,18.9862,19.386,79.4585,78.6957,79.0414,28.3147
Europe & Central Asia (excluding high income)_1993,NaN,98.0016,96.4064,98.9942,93.4961,92.25,94.7009,-12.44,1.14946e+12,5.17786e+11,...,63.3306,0.4121,4.59961e+09,20.1119,19.7791,19.9281,79.2855,77.8831,78.5118,28.0203
Europe & Central Asia (excluding high income)_1994,NaN,98.1383,96.6744,99.0479,93.1017,91.7995,94.3593,-12.8081,1.00223e+12,4.32406e+11,...,63.399,0.261489,8.05576e+09,21.145,20.3129,20.6868,78.2396,77.3118,77.7291,28.6672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe_1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.37973e+09,...,26.809,6.13255,1.56487e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe_1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.82878e+09,...,28.25,5.66155,2.92322e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe_1990,NaN,30.3578,7.83181,85.5399,NaN,NaN,NaN,NaN,NaN,8.3094e+09,...,28.988,5.37279,6.89136e+06,NaN,NaN,NaN,NaN,NaN,NaN,51.2
Zimbabwe_1991,NaN,30.7188,7.51522,85.5419,NaN,NaN,NaN,NaN,NaN,8.1205e+09,...,29.738,5.07489,0,81.843,46.904,63.146,17.992,52.6,36.512,51.9
Zimbabwe_1992,NaN,28.2,3.03592,85.5438,NaN,NaN,NaN,NaN,NaN,6.28385e+09,...,30.499,4.79736,2.1615e+08,81.747,47.136,63.28,18.092,52.38,36.386,52.5
Zimbabwe_1993,NaN,31.4367,7.19543,85.5446,NaN,NaN,NaN,NaN,NaN,6.14909e+09,...,30.94,3.50053,2.8158e+08,82.103,47.487,63.712,17.735,52.022,35.95,53
Zimbabwe_1994,NaN,28.1,3.4,80.4,NaN,NaN,NaN,NaN,NaN,6.37077e+09,...,31.335,3.1866,3.75911e+08,82.043,47.137,63.589,17.791,52.366,36.07,53.4
Zimbabwe_1995,NaN,32.1301,7.30475,85.5391,NaN,NaN,NaN,NaN,NaN,6.52328e+09,...,31.732,3.07206,4.60812e+08,80.757,46.294,62.622,19.045,53.149,36.991,53.7
Zimbabwe_1996,NaN,32.4599,7.33369,85.5307,NaN,NaN,NaN,NaN,NaN,7.92377e+09,...,32.132,2.9859,4.37236e+08,79.438,45.025,61.387,20.318,54.33,38.16,54
Zimbabwe_1997,NaN,32.7745,7.34058,85.5171,NaN,NaN,NaN,NaN,NaN,7.74922e+09,...,32.534,2.89423,3.85255e+08,78.01,44.12,60.287,21.698,55.159,39.196,54.3
Zimbabwe_1998,NaN,33.0708,7.31988,85.4973,84.0973,84.9928,83.2078,NaN,NaN,5.82615e+09,...,32.939,2.79018,4.07171e+08,77.611,44.54,60.204,22.181,54.795,39.347,54.6
Zimbabwe_1999,NaN,38.4,8.3,87.4,86.2809,86.9005,85.6659,NaN,NaN,6.33237e+09,...,33.347,2.66078,3.8293e+08,77.246,45.158,60.267,22.608,54.239,39.345,54.9
Zimbabwe_2000,32.4,33.5974,7.17977,85.4358,87.0279,87.3481,86.7101,NaN,NaN,6.14702e+09,...,33.758,2.52374,2.9395e+08,77.001,46.118,60.751,22.806,53.278,38.839,55.3
Zimbabwe_2001,32.25,33.8309,7.06538,85.3957,89.0451,89.695,88.4001,NaN,NaN,6.28625e+09,...,34.17,2.38368,2.7477e+08,76.675,46.943,61.126,23.071,52.456,38.439,55.6
Zimbabwe_2002,32.18,34.2,7.15528,85.3531,85.5063,86.1623,84.8555,NaN,NaN,5.89446e+09,...,34.585,2.28785,2.94113e+08,76.498,48.362,61.876,23.178,51.058,37.667,55.9
Zimbabwe_2003,32.01,34.2668,7.40605,85.3107,84.1375,85.0466,83.2353,NaN,NaN,5.29971e+09,...,34.479,0.7543,3.16711e+08,76.453,49.548,62.559,23.227,49.864,36.983,56.2
Zimbabwe_2004,31.77,34.4814,7.97256,85.2713,NaN,NaN,NaN,NaN,NaN,5.23297e+09,...,34.294,0.592337,3.09047e+08,76.057,49.878,62.621,23.619,49.513,36.908,56.5
Zimbabwe_2005,31.64,34.7018,8.54036,85.2377,NaN,NaN,NaN,NaN,NaN,5.21588e+09,...,34.11,0.725921,1.25085e+08,75.462,50.108,62.476,24.211,49.27,37.045,56.8
Zimbabwe_2006,31.34,37.2,8.7,91.4,NaN,NaN,NaN,NaN,NaN,4.77448e+09,...,33.926,0.87283,1.28124e+08,74.879,50.281,62.294,24.789,49.08,37.218,57
Zimbabwe_2007,31.17,35.1845,9.71319,85.1993,NaN,NaN,NaN,NaN,NaN,4.47293e+09,...,33.743,1.01386,1.3446e+08,75.441,52.047,63.474,24.236,47.313,36.041,57.2
Zimbabwe_2008,30.97,35.4573,10.3317,85.1994,NaN,NaN,NaN,NaN,NaN,3.60049e+09,...,33.56,1.1563,1.29426e+08,76.235,54.514,65.12,23.455,44.852,34.404,57.4
Zimbabwe_2009,30.81,43.3691,17.4528,90.8619,NaN,NaN,NaN,NaN,8.72443e+09,7.98407e+09,...,33.378,1.29872,5.42317e+08,76.077,54.843,65.192,23.607,44.5,34.316,57.4
Zimbabwe_2010,30.46,36.0631,11.6286,85.2352,NaN,NaN,NaN,12.6436,9.8275e+09,9.8275e+09,...,33.196,1.42999,5.28729e+08,75.87,55.324,65.335,23.813,44.012,34.17,58.2
Zimbabwe_2011,30.27,36.9,13.3,83.2,NaN,NaN,NaN,1.79351,1.00038e+10,1.07083e+10,...,33.015,1.56293,5.27095e+08,75.527,55.701,65.361,24.158,43.638,34.147,58.4
Zimbabwe_2012,30.02,36.7289,12.9816,85.3068,88.0634,88.9841,87.1468,12.3758,1.12418e+10,1.2253e+10,...,32.834,1.67857,5.20124e+08,75.243,56.224,65.504,24.446,43.119,34.008,58.6
Zimbabwe_2013,29.88,37.0768,13.6699,85.3515,85.2292,86.0046,84.4572,9.94562,1.23599e+10,1.47551e+10,...,32.654,1.75963,5.19342e+08,75.217,56.172,65.469,24.475,43.183,34.05,58.8
Zimbabwe_2014,29.63,32.3,9.8,83.4,NaN,NaN,NaN,3.57762,1.28021e+10,1.51298e+10,...,32.504,1.88439,4.86729e+08,75.304,56.225,65.544,24.39,43.134,33.979,58.9
Zimbabwe_2015,29.36,33.7,9.7,81.2,NaN,NaN,NaN,9.43032,1.40093e+10,1.51581e+10,...,32.385,1.97887,4.63753e+08,75.403,56.284,65.626,24.291,43.077,33.899,58.9
Zimbabwe_2016,29.05,38.1451,15.5756,85.5002,NaN,NaN,NaN,-0.486362,1.39412e+10,1.55547e+10,...,32.296,2.06086,4.55165e+08,75.477,56.314,65.676,24.218,43.049,33.849,59
Zimbabwe_2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.94627,1.42125e+10,1.62718e+10,...,32.237,2.14001,4.82185e+08,75.505,56.199,65.636,24.189,43.162,33.888,59.1

With a threshold of at least 35%, less than 30% of the rows are kept. This could be one approach to be used, the other one could be to leave them as is, and imputate the values by filling the null values with a given value - for instance the mean of the column. This however is not typically recommended as this might skew the data toward these values, further more there might be features in which the mean won't make sense and a domain expert will have to make the assessment on a case by case basis.

For example, if the GDP was to be averaged, there might be a situation in which there is a missing value for a country in which by its size, the GDP will not be nearly the world's average GDP. However to treat this will be cumbersome, time consuming, and will require a domain expert. So the risk is acknowledged, and the analysis will proceed accordingly.

In [16]:
trial_df = data_wo_null_columns.fillna(data_wo_null_columns.mean())
trial_df.isna().sum().unique()

array([0], dtype=int64)

There are no null values anymore.

In [17]:
data_wo_nulls = trial_df

The next step is to incorporate the Human Development Index by country and year into the DataFrame. The operation should be actually performed on the full Data Frame (data) since the HDI data only encompasses years 1990 onward, so 30 years worth of information will be lost from the Data Frame. It is a safer approach to drop the null values after this merger occurs.

Before that, some more preprocessing has to be performed on the full Data Frame.

In [18]:
indeces = list(map(lambda x: x.split('_'),data.index))
countries = list(map(lambda x: x[0], indeces))
years = list(map(lambda x: x[1], indeces))

data['year'] = years
data['countries'] = countries
data.head()

,"2005 PPP conversion factor, GDP (LCU per international $)","2005 PPP conversion factor, private consumption (LCU per international $)",Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+),"Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)",...,Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%),year,countries
Arab World_1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960,Arab World
Arab World_1961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1961,Arab World
Arab World_1962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1962,Arab World
Arab World_1963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1963,Arab World
Arab World_1964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1964,Arab World

Mapped country and years as separate columns for better hadnling on indexing, mergers, etc.

Then read the HDI file to be merged with the data.

In [19]:
HDI_df = pd.read_excel('2018_all_indicators.xlsx')
HDI_df = HDI_df.loc[HDI_df['indicator_name'] == 'Human Development Index (HDI)']
HDI_df.head()

,dimension,indicator_id,indicator_name,iso3,country_name,1990,1991,1992,1993,1994,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,9999
189,Composite indices,137506,Human Development Index (HDI),AFG,Afghanistan,NaN,NaN,NaN,NaN,NaN,...,0.453,0.463,0.471,0.482,0.487,0.491,0.493,0.494,0.498,0.498
190,Composite indices,137506,Human Development Index (HDI),ALB,Albania,0.645,0.626,0.610,0.613,0.619,...,0.729,0.741,0.752,0.767,0.771,0.773,0.776,0.782,0.785,0.785
191,Composite indices,137506,Human Development Index (HDI),DZA,Algeria,0.577,0.581,0.587,0.591,0.595,...,0.719,0.729,0.736,0.740,0.745,0.747,0.749,0.752,0.754,0.754
192,Composite indices,137506,Human Development Index (HDI),AND,Andorra,NaN,NaN,NaN,NaN,NaN,...,0.830,0.828,0.827,0.849,0.850,0.853,0.854,0.856,0.858,0.858
193,Composite indices,137506,Human Development Index (HDI),AGO,Angola,NaN,NaN,NaN,NaN,NaN,...,0.522,0.520,0.534,0.543,0.554,0.564,0.572,0.577,0.581,0.581

Dropping columns: dimension, indicator_id, indicator_name (Only HDI was used), and iso3.

In [20]:
HDI_df.index = HDI_df['country_name']
HDI_df = HDI_df[HDI_df.columns[5:]]
HDI_df = HDI_df.T
HDI_df.head()

country_name,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,United Kingdom,United States,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Yemen,Zambia,Zimbabwe
1990,NaN,0.645,0.577,NaN,NaN,NaN,0.704,0.631,0.866,0.795,...,0.775,0.860,0.692,NaN,NaN,0.634,0.475,0.399,0.401,0.491
1991,NaN,0.626,0.581,NaN,NaN,NaN,0.713,0.628,0.867,0.800,...,0.788,0.861,0.697,NaN,NaN,0.644,0.484,0.403,0.402,0.494
1992,NaN,0.610,0.587,NaN,NaN,NaN,0.720,0.580,0.868,0.805,...,0.801,0.867,0.700,NaN,NaN,0.651,0.496,0.405,0.403,0.481
1993,NaN,0.613,0.591,NaN,NaN,NaN,0.725,0.588,0.872,0.807,...,0.814,0.871,0.703,NaN,NaN,0.653,0.506,0.408,0.409,0.476
1994,NaN,0.619,0.595,NaN,NaN,NaN,0.728,0.599,0.875,0.813,...,0.827,0.875,0.709,NaN,NaN,0.654,0.517,0.409,0.408,0.473

In [21]:
import functools
import operator

trial_df = pd.DataFrame()

# https://stackoverflow.com/questions/952914/how-to-make-a-flat-list-out-of-list-of-lists

a = list(map(lambda x: list(map(lambda y: [x,y],HDI_df.index)), HDI_df.columns))
b = functools.reduce(operator.iconcat, a, [])
trial_df['countries'] = list(map(lambda x: x[0], b))
trial_df['year'] = list(map(lambda x: x[1], b))
trial_df = trial_df[trial_df['year'] != 9999]
trial_df['HDI'] = list(map(lambda x,y: HDI_df[x][y],trial_df['countries'],trial_df['year']))
trial_df.head()

     countries  year  HDI
0  Afghanistan  1990  NaN
1  Afghanistan  1991  NaN
2  Afghanistan  1992  NaN
3  Afghanistan  1993  NaN
4  Afghanistan  1994  NaN

The trial_df has the mapped HDI indeces for every country per year from 1990 to 2017.

In [22]:
HDI_df = trial_df

In [23]:
HDI_df['year'] = HDI_df['year'].astype('int')
data['year'] = data['year'].astype('int')

In [24]:
data = data[data['year'] >= 1990]
data.head()

,"2005 PPP conversion factor, GDP (LCU per international $)","2005 PPP conversion factor, private consumption (LCU per international $)",Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+),"Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)",...,Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%),year,countries
Arab World_1990,NaN,NaN,NaN,74.3842,57.7703,92.2955,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.4512,1990,Arab World
Arab World_1991,NaN,NaN,NaN,74.3822,61.4057,92.2727,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.7681,1991,Arab World
Arab World_1992,NaN,NaN,NaN,74.3132,61.9606,91.5987,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.6211,1992,Arab World
Arab World_1993,NaN,NaN,NaN,75.3493,63.0471,92.4256,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.421,1993,Arab World
Arab World_1994,NaN,NaN,NaN,75.7885,63.5731,92.6288,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994,Arab World

In [25]:
temp_df1 = data[data['year'] != 2018].copy().reset_index(drop=True)
temp_df2 = HDI_df.copy().reset_index(drop=True)

In [26]:

index_list = []
for i in range(len(temp_df1)):

    if(temp_df1['countries'].iloc[i] not in temp_df2['countries'].values):
        index_list.append(i)
    
temp_df1.drop(index=index_list, inplace = True)

In [27]:

index_list2 = []
for i in range(len(temp_df2)):

    if(temp_df2['countries'].iloc[i] not in temp_df1['countries'].values):
        index_list2.append(i)

temp_df2.drop(index = index_list2, inplace=True)

In [28]:
temp_df1['HDI'] = temp_df2['HDI'].values

In [29]:
data_HDI = temp_df1.reset_index(drop=True)

In [30]:
data_HDI

,"2005 PPP conversion factor, GDP (LCU per international $)","2005 PPP conversion factor, private consumption (LCU per international $)",Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+),"Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)","Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)",...,Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%),year,countries,HDI
0,NaN,NaN,NaN,0.01,NaN,52.037,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1990,Afghanistan,NaN
1,NaN,NaN,NaN,0.01,NaN,53.8098,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1991,Afghanistan,NaN
2,NaN,NaN,NaN,0.01,NaN,55.5825,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1992,Afghanistan,NaN
3,NaN,NaN,NaN,0.01,NaN,57.3542,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993,Afghanistan,NaN
4,NaN,NaN,NaN,0.01,NaN,59.1238,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994,Afghanistan,NaN
5,NaN,NaN,NaN,0.01,NaN,60.8903,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,Afghanistan,NaN
6,NaN,NaN,NaN,0.01,NaN,62.6527,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996,Afghanistan,NaN
7,NaN,NaN,NaN,0.01,NaN,64.4099,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1997,Afghanistan,NaN
8,NaN,NaN,NaN,0.0219771,NaN,66.1609,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1998,Afghanistan,NaN
9,NaN,NaN,NaN,0.179635,NaN,67.9048,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999,Afghanistan,NaN
10,NaN,NaN,8.8,0.959756,NaN,69.641,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000,Afghanistan,NaN
11,NaN,NaN,9.51,0.776537,NaN,71.3718,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,Afghanistan,NaN
12,NaN,NaN,10.39,6.26739,NaN,73.1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002,Afghanistan,0.373
13,NaN,NaN,11.46,11.752,NaN,74.8284,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003,Afghanistan,0.383
14,NaN,NaN,12.43,17.2363,NaN,76.5598,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004,Afghanistan,0.398
15,15.1322,16.7097,13.49,23,13,74,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005,Afghanistan,0.408
16,NaN,NaN,14.81,28.2286,12.5439,80.0429,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006,Afghanistan,0.417
17,NaN,NaN,15.99,33.7487,18.9162,81.8003,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007,Afghanistan,0.429
18,NaN,NaN,17.44,42.4,32.5,89.9,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,39,NaN,2008,Afghanistan,0.437
19,NaN,NaN,18.84,44.8549,31.8452,85.3545,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009,Afghanistan,0.453
20,NaN,NaN,20.68,42.7,32.4,82.8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010,Afghanistan,0.463
21,NaN,NaN,22.33,43.222,33.3801,86.5678,9.00501,2.61623,15.4155,10.5389,...,NaN,NaN,NaN,NaN,NaN,40.4,NaN,2011,Afghanistan,0.471
22,NaN,NaN,24.08,69.1,63.8,95,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,Afghanistan,0.482
23,NaN,NaN,26.17,67.2596,58.4237,92.5773,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,Afghanistan,0.487
24,NaN,NaN,27.99,89.5,87.8,98.7,9.961,3.81243,15.7847,11.5084,...,NaN,NaN,NaN,NaN,NaN,32.8,NaN,2014,Afghanistan,0.491
25,NaN,NaN,30.1,71.5,64.2,92.5,NaN,NaN,NaN,NaN,...,18.2,66.9,48.4,33.4,8.8,34.8,NaN,2015,Afghanistan,0.493
26,NaN,NaN,32.44,84.1371,78.9611,98.0384,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016,Afghanistan,0.494
27,NaN,NaN,NaN,NaN,NaN,NaN,14.8933,7.16068,22.5365,18.0165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,Afghanistan,0.498
28,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,21.4,1990,Albania,0.645
29,NaN,NaN,NaN,100,100,100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,21.1,1991,Albania,0.626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4534,NaN,NaN,16.43,27.2193,2.65775,62.0154,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,59.6,2016,Zambia,0.586
4535,NaN,NaN,NaN,NaN,NaN,NaN,45.8633,40.2789,51.6809,48.3381,...,NaN,NaN,NaN,NaN,NaN,NaN,59.7,2017,Zambia,0.588
4536,NaN,NaN,NaN,30.3578,7.83181,85.5399,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,51.2,1990,Zimbabwe,0.491
4537,NaN,NaN,NaN,30.7188,7.51522,85.5419,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,51.9,1991,Zimbabwe,0.494
4538,NaN,NaN,NaN,28.2,3.03592,85.5438,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,52.5,1992,Zimbabwe,0.481
4539,NaN,NaN,NaN,31.4367,7.19543,85.5446,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53,1993,Zimbabwe,0.476
4540,NaN,NaN,NaN,28.1,3.4,80.4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,6.4,31,53.4,1994,Zimbabwe,0.473
4541,NaN,NaN,NaN,32.1301,7.30475,85.5391,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,53.7,1995,Zimbabwe,0.467
4542,NaN,NaN,NaN,32.4599,7.33369,85.5307,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,54,1996,Zimbabwe,0.466
4543,NaN,NaN,NaN,32.7745,7.34058,85.5171,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,54.3,1997,Zimbabwe,0.459
4544,NaN,NaN,NaN,33.0708,7.31988,85.4973,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,54.6,1998,Zimbabwe,0.453
4545,NaN,NaN,NaN,38.4,8.3,87.4,NaN,NaN,NaN,NaN,...,12,27.8,31.2,22.3,4.6,28.7,54.9,1999,Zimbabwe,0.448
4546,NaN,NaN,32.4,33.5974,7.17977,85.4358,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,55.3,2000,Zimbabwe,0.440
4547,NaN,NaN,32.25,33.8309,7.06538,85.3957,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,55.6,2001,Zimbabwe,0.442
4548,NaN,NaN,32.18,34.2,7.15528,85.3531,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,55.9,2002,Zimbabwe,0.435
4549,NaN,NaN,32.01,34.2668,7.40605,85.3107,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,56.2,2003,Zimbabwe,0.428
4550,NaN,NaN,31.77,34.4814,7.97256,85.2713,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,56.5,2004,Zimbabwe,0.428
4551,NaN,NaN,31.64,34.7018,8.54036,85.2377,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,56.8,2005,Zimbabwe,0.430
4552,NaN,NaN,31.34,37.2,8.7,91.4,NaN,NaN,NaN,NaN,...,12.2,33,30.2,24.3,4.6,33.6,57,2006,Zimbabwe,0.435
4553,NaN,NaN,31.17,35.1845,9.71319,85.1993,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,57.2,2007,Zimbabwe,0.442
4554,NaN,NaN,30.97,35.4573,10.3317,85.1994,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,57.4,2008,Zimbabwe,0.439
4555,NaN,NaN,30.81,43.3691,17.4528,90.8619,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,30.1,57.4,2009,Zimbabwe,0.450
4556,NaN,NaN,30.46,36.0631,11.6286,85.2352,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,58.2,2010,Zimbabwe,0.467
4557,NaN,NaN,30.27,36.9,13.3,83.2,39.6512,37.1244,42.5456,50.0355,...,7.5,22.3,21.4,16.9,3.9,30.5,58.4,2011,Zimbabwe,0.478
4558,NaN,NaN,30.02,36.7289,12.9816,85.3068,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,58.6,2012,Zimbabwe,0.505
4559,NaN,NaN,29.88,37.0768,13.6699,85.3515,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,58.8,2013,Zimbabwe,0.516
4560,NaN,NaN,29.63,32.3,9.8,83.4,32.3893,28.9797,35.9539,36.8856,...,NaN,NaN,NaN,NaN,NaN,33.5,58.9,2014,Zimbabwe,0.525
4561,NaN,NaN,29.36,33.7,9.7,81.2,NaN,NaN,NaN,NaN,...,8.1,22.8,21.4,14.5,3.7,32.4,58.9,2015,Zimbabwe,0.529
4562,NaN,NaN,29.05,38.1451,15.5756,85.5002,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,59,2016,Zimbabwe,0.532
4563,NaN,NaN,NaN,NaN,NaN,NaN,55.2851,51.6649,59.2275,58.8771,...,NaN,NaN,NaN,NaN,NaN,NaN,59.1,2017,Zimbabwe,0.535

Now the same rationale to delete nulls can be applied to the Data Frame to be used for the HDI question.

In [31]:
data_HDI_wo_null_columns = data_HDI[list(filter(lambda x: sum(data_HDI[x].isna())/len(data_HDI) < 0.8, data_HDI.columns))]
len(data_HDI_wo_null_columns.columns)

1202

In [32]:
threshold = 0.35
data_HDI_wo_null_columns.dropna(how = 'any', inplace = False, thresh=(1202-(threshold*1202)))

,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)","Adjusted net enrollment rate, primary (% of primary school age children)","Adjusted net enrollment rate, primary, female (% of primary school age children)","Adjusted net enrollment rate, primary, male (% of primary school age children)",Adjusted net national income (annual % growth),Adjusted net national income (constant 2010 US$),Adjusted net national income (current US$),...,"Vulnerable employment, female (% of female employment) (modeled ILO estimate)","Vulnerable employment, male (% of male employment) (modeled ILO estimate)","Vulnerable employment, total (% of total employment) (modeled ILO estimate)","Wage and salaried workers, female (% of female employment) (modeled ILO estimate)","Wage and salaried workers, male (% of male employment) (modeled ILO estimate)","Wage and salaried workers, total (% of total employment) (modeled ILO estimate)",Women's share of population ages 15+ living with HIV (%),year,countries,HDI
17,15.99,33.7487,18.9162,81.8003,NaN,NaN,NaN,NaN,NaN,NaN,...,96.635,87.806,90.691,3.252,11.519,8.817,NaN,2007,Afghanistan,0.429
18,17.44,42.4,32.5,89.9,NaN,NaN,NaN,NaN,NaN,NaN,...,96.557,87.687,90.592,3.329,11.643,8.92,NaN,2008,Afghanistan,0.437
19,18.84,44.8549,31.8452,85.3545,NaN,NaN,NaN,NaN,NaN,1.09574e+10,...,96.558,87.416,90.396,3.328,11.902,9.107,NaN,2009,Afghanistan,0.453
20,20.68,42.7,32.4,82.8,NaN,NaN,NaN,NaN,1.39304e+10,1.39304e+10,...,96.481,87.259,90.263,3.405,12.069,9.246,NaN,2010,Afghanistan,0.463
21,22.33,43.222,33.3801,86.5678,NaN,NaN,NaN,NaN,NaN,1.55842e+10,...,96.391,87.066,90.122,3.493,12.257,9.385,NaN,2011,Afghanistan,0.471
22,24.08,69.1,63.8,95,NaN,NaN,NaN,NaN,NaN,1.72877e+10,...,96.281,86.775,89.919,3.599,12.538,9.581,NaN,2012,Afghanistan,0.482
23,26.17,67.2596,58.4237,92.5773,NaN,NaN,NaN,NaN,NaN,1.77791e+10,...,96.152,86.664,89.842,3.724,12.652,9.661,NaN,2013,Afghanistan,0.487
24,27.99,89.5,87.8,98.7,NaN,NaN,NaN,NaN,NaN,1.76824e+10,...,96.028,86.514,89.744,3.844,12.797,9.758,NaN,2014,Afghanistan,0.491
25,30.1,71.5,64.2,92.5,NaN,NaN,NaN,NaN,NaN,1.72851e+10,...,95.906,86.378,89.655,3.963,12.926,9.844,NaN,2015,Afghanistan,0.493
26,32.44,84.1371,78.9611,98.0384,NaN,NaN,NaN,NaN,NaN,1.64829e+10,...,95.787,86.267,89.58,4.077,13.03,9.914,NaN,2016,Afghanistan,0.494
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.6917e+10,...,95.665,86.131,89.487,4.194,13.159,10.003,NaN,2017,Afghanistan,0.498
33,NaN,100,100,100,NaN,NaN,NaN,NaN,NaN,2.25855e+09,...,66.541,59.869,62.782,32.743,35.796,34.464,27.5,1995,Albania,0.632
34,NaN,100,100,100,NaN,NaN,NaN,NaN,3.17226e+09,3.06061e+09,...,66.1,59.783,62.509,33.173,35.903,34.725,27.7,1996,Albania,0.641
35,NaN,100,100,100,NaN,NaN,NaN,-21.9069,2.47732e+09,2.12629e+09,...,65.776,59.677,62.302,33.513,36.045,34.955,28.8,1997,Albania,0.641
36,NaN,100,100,100,NaN,NaN,NaN,22.9729,3.04643e+09,2.41694e+09,...,65.24,59.16,61.727,34.018,36.461,35.43,28.4,1998,Albania,0.652
37,NaN,100,100,100,97.282,95.9065,98.5981,34.3437,4.09268e+09,3.05181e+09,...,64.511,58.424,60.939,34.732,37.185,36.171,28.4,1999,Albania,0.662
38,39.8,100,100,100,95.8597,95.1752,96.509,10.6205,4.52734e+09,3.31979e+09,...,63.762,57.718,60.188,35.475,37.892,36.904,28.7,2000,Albania,0.669
39,42.7,100,100,100,94.327,94.1609,94.4839,10.7142,5.01241e+09,3.74292e+09,...,62.918,57.001,59.41,36.298,38.554,37.635,29,2001,Albania,0.676
40,45.23,100,100,100,NaN,NaN,NaN,8.00616,5.41371e+09,4.09824e+09,...,61.986,56.339,58.642,37.211,39.17,38.371,29.1,2002,Albania,0.682
41,47.62,100,100,100,92.1188,91.8248,92.3935,10.0809,5.95946e+09,5.2984e+09,...,60.994,55.653,57.845,38.175,39.775,39.118,29.3,2003,Albania,0.689
42,50.53,100,100,100,91.3179,91.5802,91.0729,13.4098,6.75862e+09,6.75755e+09,...,60.014,55.02,57.083,39.126,40.335,39.835,29.5,2004,Albania,0.694
43,53.25,100,100,100,NaN,NaN,NaN,7.87222,7.29067e+09,7.5313e+09,...,59.041,54.405,56.333,40.07,40.877,40.542,29.5,2005,Albania,0.704
44,55.57,100,100,100,NaN,NaN,NaN,8.4603,7.90748e+09,8.40599e+09,...,58.074,53.801,55.588,41.007,41.407,41.24,29.6,2006,Albania,0.711
45,58.14,100,100,100,NaN,NaN,NaN,7.13305,8.47153e+09,9.90203e+09,...,57.132,53.249,54.881,41.919,41.893,41.904,29.6,2007,Albania,0.720
46,60.75,100,100,100,87.1512,86.9598,87.3293,11.789,9.47024e+09,1.1677e+10,...,66.658,52.441,58.424,32.767,44.96,39.829,29.5,2008,Albania,0.724
47,63.24,100,100,100,85.7096,85.2437,86.1422,2.93053,9.74776e+09,1.06044e+10,...,64.9,50.719,56.473,34.757,47.074,42.076,29.3,2009,Albania,0.729
48,65.23,100,100,100,86.2733,86.0467,86.4825,5.51114,1.0285e+10,1.0285e+10,...,62.6,49.828,55.133,36.947,47.812,43.298,29.3,2010,Albania,0.741
49,67.81,100,100,100,87.1868,87.0338,87.3269,5.74122,1.08755e+10,1.11942e+10,...,64.118,55.577,59.194,34.728,42.001,38.922,29.4,2011,Albania,0.752
50,69.96,100,100,100,90.4651,90.0385,90.8557,2.8057,1.11806e+10,1.05715e+10,...,67.01,57.317,61.535,32.007,40.739,36.94,29.6,2012,Albania,0.767
51,71.78,100,100,100,94.3662,93.9258,94.7689,4.84814,1.17226e+10,1.13988e+10,...,61.815,54.756,57.78,37.118,43.002,40.482,29.8,2013,Albania,0.771
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4525,15.08,18.5,3,47.8,89.5958,89.9867,89.2076,NaN,NaN,9.11035e+09,...,90.282,73.934,81.716,9.417,25.463,17.825,59.3,2007,Zambia,0.503
4526,15.25,22.7147,3.92903,53.5281,90.0624,NaN,NaN,NaN,NaN,1.24944e+10,...,90.198,73.94,81.667,9.592,25.664,18.026,59.4,2008,Zambia,0.517
4527,15.43,23.2356,3.78954,54.564,87.1171,88.325,85.9189,NaN,NaN,1.12947e+10,...,89.883,73.128,81.103,9.904,26.491,18.597,59.5,2009,Zambia,0.533
4528,15.47,22,3.1,49.8,84.5752,85.7253,83.435,NaN,1.35942e+10,1.35942e+10,...,89.484,72.066,80.367,10.299,27.567,19.338,59.6,2010,Zambia,0.544
4529,15.71,24.3286,3.52058,56.6661,88.4086,89.5161,87.3112,NaN,NaN,1.61411e+10,...,89.203,71.174,79.76,10.581,28.475,19.953,59.6,2011,Zambia,0.556
4530,15.9,24.8947,3.37938,57.7287,90.1253,91.5804,88.6843,NaN,NaN,1.88852e+10,...,88.908,70.455,79.24,10.874,29.209,20.479,59.6,2012,Zambia,0.569
4531,15.99,25.4697,3.22666,58.7968,87.9074,88.8706,86.9541,NaN,NaN,2.03731e+10,...,88.712,70.061,78.955,11.066,29.6,20.762,59.6,2013,Zambia,0.574
4532,16.23,27.9,3.8,61.5,NaN,NaN,NaN,NaN,NaN,2.06296e+10,...,88.509,69.697,78.686,11.266,29.96,21.028,59.6,2014,Zambia,0.580
4533,16.31,31.1,3.7,67.7,NaN,NaN,NaN,NaN,NaN,1.60796e+10,...,88.361,69.44,78.496,11.41,30.215,21.215,59.6,2015,Zambia,0.583
4534,16.43,27.2193,2.65775,62.0154,NaN,NaN,NaN,NaN,NaN,1.59083e+10,...,88.17,69.129,78.26,11.598,30.521,21.446,59.6,2016,Zambia,0.586
4535,NaN,NaN,NaN,NaN,86.0215,87.8902,84.1754,NaN,NaN,1.90344e+10,...,87.982,68.823,78.029,11.781,30.825,21.675,59.7,2017,Zambia,0.588
4537,NaN,30.7188,7.51522,85.5419,NaN,NaN,NaN,NaN,NaN,8.1205e+09,...,81.843,46.904,63.146,17.992,52.6,36.512,51.9,1991,Zimbabwe,0.494
4538,NaN,28.2,3.03592,85.5438,NaN,NaN,NaN,NaN,NaN,6.28385e+09,...,81.747,47.136,63.28,18.092,52.38,36.386,52.5,1992,Zimbabwe,0.481
4539,NaN,31.4367,7.19543,85.5446,NaN,NaN,NaN,NaN,NaN,6.14909e+09,...,82.103,47.487,63.712,17.735,52.022,35.95,53,1993,Zimbabwe,0.476
4540,NaN,28.1,3.4,80.4,NaN,NaN,NaN,NaN,NaN,6.37077e+09,...,82.043,47.137,63.589,17.791,52.366,36.07,53.4,1994,Zimbabwe,0.473
4545,NaN,38.4,8.3,87.4,86.2809,86.9005,85.6659,NaN,NaN,6.33237e+09,...,77.246,45.158,60.267,22.608,54.239,39.345,54.9,1999,Zimbabwe,0.448
4546,32.4,33.5974,7.17977,85.4358,87.0279,87.3481,86.7101,NaN,NaN,6.14702e+09,...,77.001,46.118,60.751,22.806,53.278,38.839,55.3,2000,Zimbabwe,0.440
4547,32.25,33.8309,7.06538,85.3957,89.0451,89.695,88.4001,NaN,NaN,6.28625e+09,...,76.675,46.943,61.126,23.071,52.456,38.439,55.6,2001,Zimbabwe,0.442
4548,32.18,34.2,7.15528,85.3531,85.5063,86.1623,84.8555,NaN,NaN,5.89446e+09,...,76.498,48.362,61.876,23.178,51.058,37.667,55.9,2002,Zimbabwe,0.435
4549,32.01,34.2668,7.40605,85.3107,84.1375,85.0466,83.2353,NaN,NaN,5.29971e+09,...,76.453,49.548,62.559,23.227,49.864,36.983,56.2,2003,Zimbabwe,0.428
4553,31.17,35.1845,9.71319,85.1993,NaN,NaN,NaN,NaN,NaN,4.47293e+09,...,75.441,52.047,63.474,24.236,47.313,36.041,57.2,2007,Zimbabwe,0.442
4555,30.81,43.3691,17.4528,90.8619,NaN,NaN,NaN,NaN,8.72443e+09,7.98407e+09,...,76.077,54.843,65.192,23.607,44.5,34.316,57.4,2009,Zimbabwe,0.450
4556,30.46,36.0631,11.6286,85.2352,NaN,NaN,NaN,12.6436,9.8275e+09,9.8275e+09,...,75.87,55.324,65.335,23.813,44.012,34.17,58.2,2010,Zimbabwe,0.467
4557,30.27,36.9,13.3,83.2,NaN,NaN,NaN,1.79351,1.00038e+10,1.07083e+10,...,75.527,55.701,65.361,24.158,43.638,34.147,58.4,2011,Zimbabwe,0.478
4558,30.02,36.7289,12.9816,85.3068,88.0634,88.9841,87.1468,12.3758,1.12418e+10,1.2253e+10,...,75.243,56.224,65.504,24.446,43.119,34.008,58.6,2012,Zimbabwe,0.505
4559,29.88,37.0768,13.6699,85.3515,85.2292,86.0046,84.4572,9.94562,1.23599e+10,1.47551e+10,...,75.217,56.172,65.469,24.475,43.183,34.05,58.8,2013,Zimbabwe,0.516
4560,29.63,32.3,9.8,83.4,NaN,NaN,NaN,3.57762,1.28021e+10,1.51298e+10,...,75.304,56.225,65.544,24.39,43.134,33.979,58.9,2014,Zimbabwe,0.525
4561,29.36,33.7,9.7,81.2,NaN,NaN,NaN,9.43032,1.40093e+10,1.51581e+10,...,75.403,56.284,65.626,24.291,43.077,33.899,58.9,2015,Zimbabwe,0.529
4562,29.05,38.1451,15.5756,85.5002,NaN,NaN,NaN,-0.486362,1.39412e+10,1.55547e+10,...,75.477,56.314,65.676,24.218,43.049,33.849,59,2016,Zimbabwe,0.532
4563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.94627,1.42125e+10,1.62718e+10,...,75.505,56.199,65.636,24.189,43.162,33.888,59.1,2017,Zimbabwe,0.535

Keeping rows with at most 35% null values brings 4564 rows down to 2834, but the issue of null values is still there, and so it doesn't make sense to do this before filling the remaining null values with the mean.

In [ ]:
trial_hdi_df = data_HDI_wo_null_columns.fillna(data_HDI_wo_null_columns.mean())
trial_hdi_df.isna().sum().unique()

There are no null values anymore.

In [ ]:
data_HDI = trial_hdi_df

In [ ]:
data_HDI

Now we have to encode the targets (HDI). According to https://www.tutor2u.net/economics/reference/human-development-index HDI can be categorized into three different groups:

Low: 0-0.5
Medium: 0.5-0.8
High: 0.8+

There are other ways of doing this classification but this classification has the lowest cardinality (3). The lower the cardinality the better the model should respond.

In [ ]:
data_HDI['HDI'] = data_HDI['HDI'].apply(lambda x: 0 if x<= 0.5 else 1 if x<= 0.8 else 2)

In [ ]:
print(data_HDI['HDI'].unique())

Now the data is ready to be used with machine learning algorithms.

In [ ]:
print(data_HDI['HDI'].value_counts())

In [ ]:
#Percent of each value
data_HDI['HDI'].value_counts().map(lambda x: x*100/len(data_HDI['HDI']))

The data is imbalanced, and so a stratified sampling might be in order. However the more imbalanced the data is, the more biased the model might turn out, this has to be taken into account.

In [ ]:
#https://stackoverflow.com/questions/26414913/normalize-columns-of-pandas-data-frame

max_min_df = data_HDI.copy()

x = max_min_df.iloc[:,0:-3].values 
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
max_min_df.iloc[:,0:-3] = x_scaled

In [ ]:
data_HDI = max_min_df.copy()

In [ ]:
# https://stackoverflow.com/questions/36997619/sklearn-stratified-sampling-based-on-a-column
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=0)

X1 = data_HDI.iloc[:,1:-2]
y1 = data_HDI['HDI']

for train_index, test_index in sss.split(X1, y1):
    X1_train, X1_test = X1.iloc[train_index,:].values, X1.iloc[test_index, :].values
    y1_train, y1_test = y1[train_index], y1[test_index]

Random forest classifier has been given some initial fixed parameters (number of classifiers = 100). The rest of them will be changed by means of the for loop.

Criteria: GINI or Entropy<br>
Max depth: iterate from 1 to 15

In [ ]:
criteria = ['gini', 'entropy']
max_depth = 15

forest_df1 = pd.DataFrame(columns = ['Criterion', 'Max Depth', 'Train Score', 'Test Score'])

for j in range(len(criteria)):
    for i in range(1,max_depth+1):
        print(datetime.now())
        forest1 = RandomForestClassifier(criterion=criteria[j], random_state=0, max_depth=i, n_estimators=100).fit(X1_train, y1_train)
        score_train = forest1.score(X1_train, y1_train)
        score_test = forest1.score(X1_test, y1_test)
        forest_df1.loc[(i-1)+(j*max_depth+1)] = [criteria[j], i, score_train, score_test]

In [ ]:
forest_df1

In [ ]:
forest_df1.to_csv('Table1.csv', index=False)

In [ ]:
plt.style.use('seaborn-whitegrid')
fig, ax = plt.subplots(2, figsize=(12, 16))
plt.subplots_adjust(hspace = 0.3)

ax[0].plot(forest_df1['Max Depth'].loc[forest_df1['Criterion'] == 'gini'], forest_df1['Train Score'].loc[forest_df1['Criterion'] == 'gini'])
ax[0].plot(forest_df1['Max Depth'].loc[forest_df1['Criterion'] == 'gini'], forest_df1['Test Score'].loc[forest_df1['Criterion'] == 'gini'])
ax[0].set(xlim=(0, 16), ylim=(0.70, 1.01),xlabel='Max Depth', ylabel='Score Ratio',title=f'Train and Test Score vs Max Depth using Gini Index', xticks=list(range(0,31,2)))
ax[0].legend(['Training', 'Test'])

ax[1].plot(forest_df1['Max Depth'].loc[forest_df1['Criterion'] == 'entropy'], forest_df1['Train Score'].loc[forest_df1['Criterion'] == 'entropy'])
ax[1].plot(forest_df1['Max Depth'].loc[forest_df1['Criterion'] == 'entropy'], forest_df1['Test Score'].loc[forest_df1['Criterion'] == 'entropy'])
ax[1].set(xlim=(0, 16), ylim=(0.70, 1.01),xlabel='Max Depth', ylabel='Score Ratio',title=f'Train and Test Score vs Max Depth using Entropy',xticks=list(range(0,31,2)))
ax[1].legend(['Training', 'Test'])


plt.savefig('Decision Tree Scores.png')
plt.show()

In [ ]:
best_forest1 = RandomForestClassifier(criterion='entropy', random_state=0, max_depth=9, n_estimators=100).fit(X1_train, y1_train)
importance1 = best_forest1.feature_importances_
names1 = data_HDI.columns[:-3]
importance_df = pd.DataFrame(data={'Feature name': names1, 'Ratio of importance': importance1}).sort_values(ascending=False, by='Ratio of importance').reset_index(drop=True)

In [ ]:
pred1 = best_forest1.predict(X1_test)
print('Mean Absolute Error:', metrics.mean_absolute_error(y1_test, pred1))  
print('Mean Squared Error:', metrics.mean_squared_error(y1_test, pred1))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y1_test, pred1)))
print('Model Accuracy:', best_forest1.score(X1_test, y1_test))

In [ ]:
#https://stackoverflow.com/questions/39662398/scikit-learn-output-metrics-classification-report-into-csv-tab-delimited-format

class_report = pd.DataFrame(classification_report(y1_test,pred1, output_dict=True)).T
class_report.to_csv('Q1-ClasRepo.csv')
class_report

In [ ]:
mat = confusion_matrix(y1_test, pred1)
sns.heatmap(mat.T, square=True, annot=True, fmt='d', cbar=False,
            xticklabels = data_HDI['HDI'].unique(),
            yticklabels = data_HDI['HDI'].unique())
plt.xlabel('True label')
plt.ylabel('Predicted label')
plt.savefig('Q1-Conf_Matr.png')
plt.show()

In [ ]:
importance_df

In [ ]:
top_10 = importance_df.head(10)
top_10.index = range(1,11)
top_10.to_csv('Top_10_features.csv', index=True)
top_10

In [ ]:
sum(top_10['Ratio of importance'])

In [ ]:
importance_df[importance_df['Ratio of importance'] > 0.001]

In [ ]:
gini_importance = importance_df[importance_df['Ratio of importance'] > 0.001]['Feature name']
'GINI index (World Bank estimate)' in gini_importance

This is interesting, the GINI index, in other words income inequality, is not a factor at the time of deciding whether a country is developed or not, at least in more than 0.1% compared to other features. Let's see what is the ranking of it in the overall features data frame.

In [ ]:
importance_df[importance_df['Feature name'] == 'GINI index (World Bank estimate)']

This represents 0.0059%. It is a factor in deciding whether a nation is developed or not, but there are at least 976 other factors with more weight than the GINI Index.

In [ ]:
my_list = list(map(lambda i: (i,importance_df.reset_index(drop=True)['Ratio of importance'].head(i).sum()),range(100,1300,100)))
num = list(map(lambda feat: feat[0], my_list))
feat = list(map(lambda feat: feat[1], my_list))
feature_importance_df = pd.DataFrame(data = {'Number of Features': num, 'Accumulated Feature Importance': feat})
feature_importance_df.to_csv('Feature_importance.csv', index=False)
feature_importance_df

In [ ]:
feature_importance_df.plot(x='Number of Features', y = 'Accumulated Feature Importance', title='Accumulated Feature Importance vs Number of features used', figsize = (12,8));

Question 2: GINI INDEX prediction:

For this question the number of features can be reduced in order to only use those which are more relevant according to the random forest. This can help enhance the regression by paying attention to the "Curse of dimensionality".

From the Data Frame and the graph above, it can be seen that by using the most important 300 features, over 85% of the importance is accounted for. So by using these a random forest regressor can be built to predict the GINI Index without taking the HDI into account.

In [ ]:
features = importance_df['Feature name'][0:300]

In [ ]:
data_GINI = data_HDI[features].copy()
data_GINI['GINI index (World Bank estimate)'] = data_HDI['GINI index (World Bank estimate)']
data_GINI['year'] = data_HDI['year']

In [ ]:
validation_2017 = data_GINI[data_GINI['year'] == 2017]
data_GINI = data_GINI[data_GINI['year'] != 2017]

In [ ]:
y2 = data_GINI['GINI index (World Bank estimate)']
data_GINI = data_GINI.drop(columns=['GINI index (World Bank estimate)', 'year'])
data_GINI.head()

In [ ]:
'GINI index (World Bank estimate)' in data_GINI_features.columns

In [ ]:
X2 = data_GINI.values
y2 = y2.values

X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.1, random_state=0)

In [ ]:
regr = RandomForestRegressor(max_depth=9, random_state=0,n_estimators=100)
regr.fit(X2_train, y2_train)

In [ ]:
pred2 = regr.predict(X2_test)
print('Mean Absolute Error:', metrics.mean_absolute_error(y2_test, pred2))  
print('Mean Squared Error:', metrics.mean_squared_error(y2_test, pred2))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y2_test, pred2)))
print('Model Accuracy:', regr.score(X2_test, y2_test))

In [ ]:
print('2017 Score/Accuracy:', regr.score(validation_2017.iloc[:,:-2], validation_2017.iloc[:,-2]))